---

- shell: snap install microk8s --classic --channel=1.18/stable
  become: yes

- shell: microk8s status --wait-ready

- shell: microk8s kubectl get nodes

- shell: microk8s kubectl get services

- shell: microk8s enable dns storage

- shell: usermod -a -G microk8s {{ lookup('env', 'USER') }}
  become: yes

- shell: chown -f -R {{ lookup('env', 'USER') }} {{ lookup('env', 'HOME') }}/.kube
  become: yes
  args:
    warn: no

- shell: microk8s kubectl completion bash >/etc/bash_completion.d/kubectl
  become: yes