---

- name: Install OutsideIT/FireMotD prerequisites
  package:
    name: "{{ item }}"
    state: present
  loop:
    - bc
    - jq
    - moreutils
    - sysstat
  become: yes

- name: Fetch FireMottD
  get_url:
    url: https://raw.githubusercontent.com/mamercad/FireMotD/mamercad/procps_unknown/FireMotD # use my fork
    dest: /tmp/FireMotD
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Run FireMotD installer
  shell: |
    ( /tmp/FireMotD -I -d && /tmp/FireMotD -G all -d ) && touch /tmp/FireMotD.installed
  args:
    creates: /tmp/FireMotD.installed
  become: yes

- name: Remove FireMotD in /etc/profile
  lineinfile:
    state: absent
    path: /etc/profile
    line: /usr/local/bin/FireMotD -T Gray
    backup: yes
  become: yes

- name: Drop FireMotD in /etc/profile.d/firemotd.sh
  lineinfile:
    path: /etc/profile.d/firemotd.sh
    line: /usr/local/bin/FireMotD -T Gray
    create: yes
    backup: yes
  become: yes
