---

# - name: upgrade everything
#   yum:
#     name: '*'
#     state: latest
#   become: yes

- name: Include FireMotD
  include_tasks: firemotd.yml

- name: Include neofetch
  include_tasks: neofetch.yml
