- name: Create grafana-image-renderer Deployment
  community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana-image-renderer
        namespace: monitoring
      spec:
        selector:
          matchLabels:
            app: grafana-image-renderer
        replicas: 1
        template:
          metadata:
            labels:
              app: grafana-image-renderer
          spec:
            containers:
              - name: app
                image: grafana/grafana-image-renderer:latest
                ports:
                  - containerPort: 8081
                    protocol: TCP
                    name: tcp-8081
                resources:
                  requests:
                    memory: "128Mi"
                    cpu: "250m"
                  limits:
                    memory: "256Mi"
                    cpu: "500m"

- name: Create grafana-image-renderer Service
  community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: grafana-image-renderer
        namespace: monitoring
      spec:
        selector:
          app: grafana-image-renderer
        ports:
          - protocol: TCP
            port: 8081
            targetPort: tcp-8081
            name: tcp-8081
        type: ClusterIP
