---

- name: Include awx vars
  include_vars:
    file: awx.yml
    name: awx
  tags: awx

- name: Include awx play
  include_tasks:
    file: awx.yml
    apply:
      tags:
        - awx
  tags:
    - awx

- name: Include common play
  include_tasks:
    file: common.yml
    apply:
      tags:
        - common
  tags:
    - common

- name: Include packages play
  include_tasks:
    file: packages.yml
    apply:
      tags:
        - apt
        - package
        - packages
  tags:
    - apt
    - package
    - packages

- name: Include updates play
  include_tasks:
    file: updates.yml
    apply:
      tags:
        - apt
        - package
        - packages
        - updates
  tags:
    - apt
    - package
    - packages
    - updates

- name: Include mark vars
  include_vars:
    file: mark.yml
    name: mark
  tags: mark

- name: Include mark play
  include_tasks:
    file: mark.yml
    apply:
      tags: mark
  tags: mark

- name: Include postfix play
  include_tasks:
    file: postfix.yml
    apply:
      tags: postfix
  tags: postfix

- name: Include Healthchecks.io play
  include_tasks:
    file: healthchecks.io.yml
    apply:
      tags:
        - healthchecks
        - healthchecks.io
  tags:
    - healthchecks
    - healthchecks.io

- name: Include netdata vars
  include_vars:
    file: netdata.yml
    name: netdata
  tags: netdata

- name: Include netdata play
  include_tasks:
    file: netdata.yml
    apply:
      tags:
        - netdata
  tags:
    - netdata

- name: Include lifecycle play
  include_tasks:
    file: lifecycle.yml
    apply:
      tags:
        - lifecycle
  tags:
    - lifecycle

- name: Include node_exporter play
  include_tasks:
    file: node_exporter.yml
    apply:
      tags:
        - node_exporter
  tags:
    - node_exporter
  when:
    - "'{{ inventory_hostname }}' not in exclude.ubuntu.node_exporter"

- name: Include additional plays
  include_tasks:
    file: "{{ item }}.yml"
    apply:
      tags:
        - plays
  tags:
    - plays
  loop: "{{ plays }}"
  when:
    - plays is defined
