---

- name: Deploy netdata apt-key
  apt_key:
    state: present
    url: https://packagecloud.io/netdata/netdata/gpgkey
  become: yes

- name: Deploy /etc/apt/sources.list.d/netdata_netdata.list
  copy:
    dest: /etc/apt/sources.list.d/netdata_netdata.list
    owner: root
    group: root
    mode: 0644
    content: |
      deb https://packagecloud.io/netdata/netdata/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main
      deb-src https://packagecloud.io/netdata/netdata/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main
  become: yes

- name: Install netdata
  apt:
    state: present
    name: netdata
    update_cache: yes
  become: yes

- name: Deploy /etc/netdata/netdata.conf
  copy:
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: 0644
    content: |
      [global]
          run as user = netdata
          history = 3600
          process scheduling policy = idle
          OOM score = 1000
      [web]
          web files owner = root
          web files group = netdata
          bind to = *
    backup: yes
  become: yes
  notify: Restart netdata

- name: Deploy health_alarm_notify.conf
  template:
    src: netdata/health_alarm_notify.conf.j2
    dest: /etc/netdata/health_alarm_notify.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart netdata

- name: Start and enable netdata
  systemd:
    name: netdata
    state: started
    enabled: yes
  become: yes

- name: Claim node to the cloud
  shell: /usr/sbin/netdata-claim.sh -token={{ netdata.netdata_claim_token }} -rooms={{ netdata.netdata_claim_room }} -url=https://app.netdata.cloud
  become: yes
  ignore_errors: yes # Might be claimed already
