---

- name: Organization
  awx.awx.tower_organization:
    state: present
    name: Cloudmason
    description: Cloudmason

- name: Team
  awx.awx.tower_team:
    state: present
    name: Cloudmason
    description: Cloudmason
    organization: Cloudmason

- name: Inventory
  awx.awx.tower_inventory:
    state: present
    name: Cloudmason
    description: Cloudmason
    organization: Cloudmason

- name: SCM Credential
  awx.awx.tower_credential:
    state: present
    name: Cloudmason SCM
    description: Cloudmason
    organization: Cloudmason
    credential_type: Source Control
    inputs:
      ssh_key_data: "{{ awx_ssh_key_data }}"
      ssh_key_unlock: "{{ awx_ssh_key_unlock }}"

- name: Machine Credential
  awx.awx.tower_credential:
    state: present
    name: Cloudmason Machine
    description: Cloudmason
    organization: Cloudmason
    credential_type: Machine
    inputs:
      username: awx
      password: "{{ awx_password }}"
      ssh_key_data: "{{ awx_ssh_key_data }}"
      ssh_key_unlock: "{{ awx_ssh_key_unlock }}"

- name: Project
  awx.awx.tower_project:
    state: present
    name: Cloudmason
    description: Cloudmason
    organization: Cloudmason
    scm_type: git
    scm_url: git@github.com:mamercad/cloudmason.git
    scm_branch: main
    scm_clean: yes
    scm_delete_on_update: yes
    scm_update_on_launch: yes
    scm_update_cache_timeout: 600
    credential: Cloudmason SCM

- name: Inventory
  awx.awx.tower_inventory:
    state: present
    name: Cloudmason
    description: Cloudmason
    organization: Cloudmason

- name: Inventory Source
  awx.awx.tower_inventory_source:
    state: present
    name: Cloudmason
    description: Cloudmason
    organization: Cloudmason
    inventory: Cloudmason
    source: scm
    source_project: Cloudmason
    source_path: ansible/inventory/cloudmason.yml
    overwrite: yes
    update_cache_timeout: 600
    update_on_project_update: yes

- name: Slack Notification Template
  awx.awx.tower_notification_template:
    name: Slack
    organization: Cloudmason
    notification_type: slack
    notification_configuration:
      channels:
        - awx
      token: "{{ slack_token }}"
    messages:
      started:
        message: "{{ '{{ job_friendly_name }} {{ job.id }} ({{ job.playbook }}) started' }}"
      success:
        message: "{{ '{{ job_friendly_name }} {{ job.id }} completed in {{ job.elapsed }} seconds' }}"
      error:
        message: "{{ '{{ job_friendly_name }} {{ job.id }} failed, please look at {{ job.url }}' }}"
    state: present

- name: Ping Job Template
  awx.awx.tower_job_template:
    state: present
    name: Ping
    job_type: run
    organization: Cloudmason
    inventory: Cloudmason
    project: Cloudmason
    playbook: ansible/playbooks/ping.yml
    credentials:
      - Cloudmason Machine
    notification_templates_started:
      - Slack
    notification_templates_success:
      - Slack
    notification_templates_error:
      - Slack

- name: Healthchecks.io Job Template
  awx.awx.tower_job_template:
    state: present
    name: Healthchecks.io
    job_type: run
    organization: Cloudmason
    inventory: Cloudmason
    project: Cloudmason
    playbook: ansible/playbooks/healthchecks.io.yml
    credentials:
      - Cloudmason Machine
    notification_templates_started:
      - Slack
    notification_templates_success:
      - Slack
    notification_templates_error:
      - Slack

- name: Pi-hole Job Template
  awx.awx.tower_job_template:
    state: present
    name: Pi-hole
    job_type: run
    organization: Cloudmason
    inventory: Cloudmason
    project: Cloudmason
    playbook: ansible/playbooks/pi-hole.yml
    credentials:
      - Cloudmason Machine
    notification_templates_started:
      - Slack
    notification_templates_success:
      - Slack
    notification_templates_error:
      - Slack

- name: Prometheus Job Template
  awx.awx.tower_job_template:
    state: present
    name: Prometheus
    job_type: run
    organization: Cloudmason
    inventory: Cloudmason
    project: Cloudmason
    playbook: ansible/playbooks/prometheus.yml
    credentials:
      - Cloudmason Machine
    notification_templates_started:
      - Slack
    notification_templates_success:
      - Slack
    notification_templates_error:
      - Slack
