---

- name: Organization
  awx.awx.tower_organization:
    state: present
    name: Cloudmason
    description: Cloudmason
  tags:
    - awx

- name: Team
  awx.awx.tower_team:
    state: present
    name: Cloudmason
    description: Cloudmason
    organization: Cloudmason
  tags:
    - awx

- name: Inventory
  awx.awx.tower_inventory:
    state: present
    name: Cloudmason
    description: Cloudmason
    organization: Cloudmason
  tags:
    - awx

- name: SCM Credential
  awx.awx.tower_credential:
    state: present
    name: Cloudmason GitHub
    description: Cloudmason
    organization: Cloudmason
    credential_type: Source Control
    inputs:
      ssh_key_data: "{{ awx_secrets.awx.ssh_key_data }}"
      ssh_key_unlock: "{{ awx_secrets.awx.ssh_key_unlock }}"
  tags:
    - awx

- name: Machine Credential
  awx.awx.tower_credential:
    state: present
    name: Cloudmason Machine / awx
    description: Cloudmason
    organization: Cloudmason
    credential_type: Machine
    inputs:
      username: awx
      password: "{{ awx_secrets.awx.password }}"
      ssh_key_data: "{{ awx_secrets.awx.ssh_key_data }}"
      ssh_key_unlock: "{{ awx_secrets.awx.ssh_key_unlock }}"
  tags:
    - awx

- name: Project
  awx.awx.tower_project:
    state: present
    name: Cloudmason
    description: Cloudmason
    organization: Cloudmason
    scm_type: git
    scm_url: git@github.com:mamercad/cloudmason.git
    scm_branch: refactor
    scm_clean: yes
    scm_delete_on_update: yes
    scm_update_on_launch: yes
    scm_update_cache_timeout: 900
    credential: Cloudmason GitHub
  tags:
    - awx

- name: Inventory
  awx.awx.tower_inventory:
    state: present
    name: Cloudmason
    description: Cloudmason
    organization: Cloudmason
  tags:
    - awx

- name: Inventory Source
  awx.awx.tower_inventory_source:
    state: present
    name: Cloudmason
    description: Cloudmason
    organization: Cloudmason
    inventory: Cloudmason
    source: scm
    source_project: Cloudmason
    source_path: ansible/inventory/cloudmason.yml
    overwrite: yes
    update_cache_timeout: 900
    update_on_project_update: yes
  tags:
    - awx

- name: Job Template
  awx.awx.tower_job_template:
    state: present
    name: Cloudmason / Ping
    job_type: run
    organization: Cloudmason
    inventory: Cloudmason
    ask_inventory_on_launch: yes
    project: Cloudmason
    playbook: ansible/playbooks/ping.yml
    credentials:
      - Cloudmason Machine
    ask_credential_on_launch: yes
    ask_limit_on_launch: yes
  tags:
    - awx

- name: Machine Credential
  awx.awx.tower_credential:
    state: present
    name: Cloudmason Machine / mamercad
    description: Cloudmason
    organization: Cloudmason
    credential_type: Machine
    inputs:
      username: mamercad
      password: "{{ awx_secrets.mark.password }}"
      ssh_key_data: "{{ awx_secrets.mark.ssh_key_data }}"
      ssh_key_unlock: "{{ awx_secrets.mark.ssh_key_unlock }}"
  tags:
    - awx

- name: Machine Credential
  awx.awx.tower_credential:
    state: present
    name: Cloudmason Machine / mark
    description: Cloudmason
    organization: Cloudmason
    credential_type: Machine
    inputs:
      username: mark
      password: "{{ awx_secrets.mark.password }}"
      ssh_key_data: "{{ awx_secrets.mark.ssh_key_data }}"
      ssh_key_unlock: "{{ awx_secrets.mark.ssh_key_unlock }}"
  tags:
    - awx

- name: Job Template
  awx.awx.tower_job_template:
    state: present
    name: Cloudmason / WAN
    job_type: run
    organization: Cloudmason
    inventory: Cloudmason
    ask_inventory_on_launch: no
    project: Cloudmason
    playbook: ansible/playbooks/wan.yml
    credentials:
      - Cloudmason Machine / mamercad
    ask_credential_on_launch: no
    limit: gateway
    ask_limit_on_launch: no
  tags:
    - awx

- name: Credential Type
  awx.awx.tower_credential_type:
    state: present
    name: Cloudmason / PowerDNS API Key
    description: Cloudmason / PowerDNS API Key
    kind: net
    inputs:
      fields:
        - type: string
          id: POWERDNS_API_KEY
          label: POWERDNS_API_KEY
          secret: true
      required:
        - POWERDNS_API_KEY
    injectors:
      env:
        POWERDNS_API_KEY: !unsafe '{{ POWERDNS_API_KEY }}'
  tags:
    - awx

- name: PowerDNS API Key Credential
  awx.awx.tower_credential:
    state: present
    name: Cloudmason PowerDNS API Key
    description: Cloudmason PowerDNS API Key
    organization: Cloudmason
    credential_type: Cloudmason / PowerDNS API Key
    inputs:
      POWERDNS_API_KEY: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        37306266393431646462663233353063356334353133383831396463393266363761636137393062
        3664663033636632303032373664656535653866356338650a393765653439343361616564663736
        30363038336163356564396162366135333431383961343730396662633539646239626332386336
        6336633833633733640a353935643532306331626538623763626438343933333735366261313538
        3832
  tags:
    - awx

- name: Credential Type
  awx.awx.tower_credential_type:
    state: present
    name: Cloudmason / CloudFlare API Key
    description: Cloudmason / CloudFlare API Key
    kind: net
    inputs:
      fields:
        - type: string
          id: CLOUDFLARE_API_KEY
          label: CLOUDFLARE_API_KEY
          secret: true
      required:
        - CLOUDFLARE_API_KEY
    injectors:
      env:
        CLOUDFLARE_API_KEY: !unsafe '{{ CLOUDFLARE_API_KEY }}'
  tags:
    - awx

- name: CloudFlare API Key Credential
  awx.awx.tower_credential:
    state: present
    name: Cloudmason CloudFlare API Key
    description: Cloudmason CloudFlare API Key
    organization: Cloudmason
    credential_type: Cloudmason / CloudFlare API Key
    inputs:
      CLOUDFLARE_API_KEY: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        61383030636463633363663834663730393033386334653932346135376134643238386134616234
        6636343065383764653433376431643737623762323332620a306134386164336138363863613739
        35373761353634633434336537383132383263326666396537656664616161626161333330633062
        3034316462346633300a323265313035616238336138666432373764656234353131396339383962
        65613864343064356331396132636261353832366132343138316461333565643137373730643233
        6132316336393732363439666561373531383065643731346532
  tags:
    - awx

- name: Credential Type
  awx.awx.tower_credential_type:
    state: present
    name: Cloudmason / CloudFlare API Token
    description: Cloudmason / CloudFlare API Token
    kind: net
    inputs:
      fields:
        - type: string
          id: CLOUDFLARE_API_TOKEN
          label: CLOUDFLARE_API_TOKEN
          secret: true
      required:
        - CLOUDFLARE_API_TOKEN
    injectors:
      env:
        CLOUDFLARE_API_TOKEN: !unsafe '{{ CLOUDFLARE_API_TOKEN }}'
  tags:
    - awx

- name: CloudFlare API Token Credential
  awx.awx.tower_credential:
    state: present
    name: Cloudmason CloudFlare API Token
    description: Cloudmason CloudFlare API Token
    organization: Cloudmason
    credential_type: Cloudmason / CloudFlare API Token
    inputs:
      CLOUDFLARE_API_TOKEN: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        61383030636463633363663834663730393033386334653932346135376134643238386134616234
        6636343065383764653433376431643737623762323332620a306134386164336138363863613739
        35373761353634633434336537383132383263326666396537656664616161626161333330633062
        3034316462346633300a323265313035616238336138666432373764656234353131396339383962
        65613864343064356331396132636261353832366132343138316461333565643137373730643233
        6132316336393732363439666561373531383065643731346532
  tags:
    - awx

- name: Job Template
  awx.awx.tower_job_template:
    state: present
    name: Cloudmason / OctoDNS
    job_type: run
    organization: Cloudmason
    inventory: Cloudmason
    ask_inventory_on_launch: no
    project: Cloudmason
    playbook: ansible/playbooks/octodns.yml
    credentials:
      - Cloudmason Machine / awx
      - Cloudmason PowerDNS API Key
      - Cloudmason CloudFlare API Key
      - Cloudmason CloudFlare API Token
    ask_credential_on_launch: no
    limit: lenovo
    ask_limit_on_launch: no
  tags:
    - awx

- name: Vault Credential
  awx.awx.tower_credential:
    state: present
    name: Cloudmason Vault
    description: Cloudmason Vault
    organization: Cloudmason
    credential_type: Vault
    inputs:
      vault_id: Cloudmason
      vault_password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        64383535393831613632353664323562653964663864383430616333376462333938626266356334
        3332343636306466623035396462633432333735653766300a663466393461633561363363326666
        34653065636366616231356661636465393661303438383730393534646131623738393332316632
        3339666535643762300a363163633138626565373565326464393835373636663733383935636133
        3764
  tags:
    - awx

- name: Job Template
  awx.awx.tower_job_template:
    state: present
    name: Cloudmason / AWX (user)
    job_type: run
    organization: Cloudmason
    inventory: Cloudmason
    ask_inventory_on_launch: no
    project: Cloudmason
    playbook: ansible/playbooks/awx-user.yml
    credentials:
      - Cloudmason Vault
      - Cloudmason Machine / mark
    ask_credential_on_launch: yes
    limit: lenovo
    ask_limit_on_launch: yes
  tags:
    - awx

- name: Workflow Job Template
  awx.awx.tower_workflow_job_template:
    state: present
    name: Cloudmason / OctoDNS Workflow
    description: Cloudmason / OctoDNS Workflow
    organization: Cloudmason
  tags:
    - awx

- name: Workflow Job Template Node
  awx.awx.tower_workflow_job_template_node:
    state: present
    identifier: octodns-sync
    workflow: Cloudmason / OctoDNS Workflow
    unified_job_template: Cloudmason / OctoDNS
    organization: Cloudmason
  tags:
    - awx

- name: Workflow Job Template Node
  awx.awx.tower_workflow_job_template_node:
    state: present
    identifier: octodns-wan
    workflow: Cloudmason / OctoDNS Workflow
    unified_job_template: Cloudmason / WAN
    organization: Cloudmason
    success_nodes:
      - octodns-sync
  tags:
    - awx

- name: Slack Notification Template
  awx.awx.tower_notification_template:
    state: present
    name: Cloudmason Slack (awx)
    organization: Cloudmason
    notification_type: slack
    notification_configuration:
      channels:
        - '#awx'
      token: "{{ awx_secrets.awx.slack_bot_oauth_token }}"
    # messages:
    #   started:
    #     message: "{{ '{{ job_friendly_name }} {{ job.id }} started [{{ job.summary_fields.project.name }}|{{ job.name }}|{{ job.playbook }}]' }}"
    #   success:
    #     message: "{{ '{{ job_friendly_name }} {{ job.id }} completed in {{ job.elapsed }} seconds' }}"
    #   error:
    #     message: "{{ '{{ job_friendly_name }} {{ job.id }} failed, please look at {{ job.url }}' }}"
  tags:
    - awx

- name: Setting TOWER_URL_BASE
  tower_settings:
    name: TOWER_URL_BASE
    value: "{{ lookup('env', 'TOWER_HOST') }}"
  tags:
    - awx

#    notification_templates_started:
#      - Slack
#    notification_templates_success:
#      - Slack
#    notification_templates_error:
#      - Slack
#
#- name: Healthchecks.io Job Template
#  awx.awx.tower_job_template:
#    state: present
#    name: Healthchecks.io
#    job_type: run
#    organization: Cloudmason
#    inventory: Cloudmason
#    project: Cloudmason
#    playbook: ansible/playbooks/healthchecks.io.yml
#    credentials:
#      - Cloudmason Machine
#    notification_templates_started:
#      - Slack
#    notification_templates_success:
#      - Slack
#    notification_templates_error:
#      - Slack
#
#- name: Pi-hole Job Template
#  awx.awx.tower_job_template:
#    state: present
#    name: Pi-hole
#    job_type: run
#    organization: Cloudmason
#    inventory: Cloudmason
#    project: Cloudmason
#    playbook: ansible/playbooks/pi-hole.yml
#    credentials:
#      - Cloudmason Machine
#    notification_templates_started:
#      - Slack
#    notification_templates_success:
#      - Slack
#    notification_templates_error:
#      - Slack
#
#- name: Prometheus Job Template
#  awx.awx.tower_job_template:
#    state: present
#    name: Prometheus
#    job_type: run
#    organization: Cloudmason
#    inventory: Cloudmason
#    project: Cloudmason
#    playbook: ansible/playbooks/prometheus.yml
#    credentials:
#      - Cloudmason Machine
#    notification_templates_started:
#      - Slack
#    notification_templates_success:
#      - Slack
#    notification_templates_error:
#      - Slack
