- name: Create awx namespace
  community.kubernetes.k8s:
    state: present
    name: awx
    api_version: v1
    kind: Namespace

# https://raw.githubusercontent.com/ansible/awx-operator/0.9.0/deploy/awx-operator.yaml
- name: Deploy awx operator
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'awx-operator/{{ item }}.yaml.j2') | from_yaml }}"
  loop:
    - CustomResourceDefinition
    - ClusterRoleBinding
    - ServiceAccount
    - ClusterRole
    - Deployment

- name: Deploy awx
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx
        namespace: awx
