---

- name: Include config
  include_tasks:
    file: config.yml
    apply:
      tags:
        - config
  tags:
    - always

- name: Include user
  include_tasks:
    file: user.yml
    apply:
      tags:
        - user
  tags:
    - always
