---

- name: Create awx group
  group:
    state: present
    name: awx
  become: yes

- name: Create awx user
  user:
    state: present
    name: awx
    groups: awx
    comment: AWX Service Account
    shell: /bin/bash
    create_home: yes
  become: yes

- name: Create ~awx/.ssh
  file:
    state: directory
    path: /home/awx/.ssh
    owner: awx
    group: awx
    mode: 0700
  become: yes

- name: Deploy ~awx/.ssh/authorized_keys
  copy:
    dest: /home/awx/.ssh/authorized_keys
    owner: awx
    group: awx
    mode: 0600
    content: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDfqDbmj069e3+TSG5oCY31aATY+iQNU9c61kGQhXjNaQyKd57krwElcV0Wp1i2tiXzVztLRBXquqstOYe38AvH9eXi1NcELauglJPNWv+UlBRjuxWUESEe0A6PGobW6Nd6c1GpIKrUgb7J/7bRhdEeXv3Irkw4Xtbamuv9lLckgH3XPiV54rgvth17iLLE1wgSkfEt64RvrP0cyOAyeLgDbu7wmr0vY+3rEA4iF80/yZW+ZzK0524eXBS1wpuKkMvhU1HJYyQhnAlEanq7pnFVd2mTXZ8PsAbrzCsjOF0I14hYlxEPWf0aonKHGAvR3J2ltY4OvzVbKnIDg1CUzR2NZILAvSoNICxE10NQuVCx5X8BpD6A8tBBBVVL9CzM7MSpCjpYh31ZX/9IaHFxCryGTSNBlMAyWvVUlu7GaL8EDv4+3ks86+YqEVmw+feoaT+Mx/mIm3tVCyV3KbXDDm6Pfg2Qfv4ny83to3Wh5b5+qafaJ0VoiIxUJWndvqN1VTTgB13OdXnAoQ454Y1YVgeH/DWYL4Nw8vow0UUdzjA+wjtP9xTyyJiEu/FIFPTib+f3uI4eyfq78fuut0pshDBdO3sh5sAtZcVRo91jCYDC8ylJDroUn7iZCmCPYCwnHr8xIWv/S82ZlL96h5LE70WQkEoQT6gpwetUOTPr/mbdkQ== Cloudmason AWX
  become: yes

- name: Give awx passwordless sudo
  copy:
    dest: /etc/sudoers.d/awx
    owner: root
    group: root
    mode: 0440
    content: |
      awx ALL=(ALL) NOPASSWD: ALL
  become: yes
