---
- name: BEW/mmid_router
  hosts: "{{ ansible_limit | default('localhost') }}"
  connection: "{{ ansible_connection | default('local') }}"
  gather_facts: no
  become: no

  vars:

    test_mmids:
      - '0'

  tasks:

    - name: Switch between stable/test trains
      assert:
        that:
          - mmid|default('0') in test_mmids
        fail_msg: Using stable train
        sucess_msg: Using test train
      register: assertion

    - set_stats:
        data:
          mmid_router:
            assertion: "{{ assertion }}"
