- name: Install the Zabbix release deb
  ansible.builtin.apt:
    state: present
    deb: "{{ zabbix_release_buster_deb }}"
  become: true
  when:
    - ansible_distribution_release == 'buster'

- name: Install the Zabbix release deb
  ansible.builtin.apt:
    state: present
    deb: "{{ zabbix_release_focal_deb }}"
  become: true
  when:
    - ansible_distribution_release == 'focal'

- name: Install Zabbix release
  ansible.builtin.apt:
    state: present
    name: zabbix-release
    update_cache: true
  become: true

- name: Install Zabbix packages
  ansible.builtin.apt:
    state: present
    name:
      - zabbix-agent
  become: true

- name: Ensure /etc/zabbix/zabbix_agentd.d exists
  ansible.builtin.file:
    state: directory
    path: /etc/zabbix/zabbix_agentd.d
    owner: root
    group: root
    mode: 0755
  become: true
  notify: restart-zabbix-agent

- name: Ensure /var/log/zabbix exists
  ansible.builtin.file:
    state: directory
    path: /var/log/zabbix
    owner: zabbix
    group: zabbix
    mode: 0755
  become: true
  notify: restart-zabbix-agent

- name: Deploy /etc/zabbix/zabbix_agentd.conf
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  notify: restart-zabbix-agent

- name: Create UserParameterDir
  ansible.builtin.file:
    state: directory
    path: "{{ user_parameter_dir }}"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Deploy /etc/zabbix/zabbix_agentd.d/user_parameter.conf
  ansible.builtin.template:
    src: user_parameter.conf.j2
    dest: /etc/zabbix/zabbix_agentd.d/user_parameter.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  notify: restart-zabbix-agent

- name: Deploy user_parameter template scripts
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/usr/local/bin/zbx_{{ item | basename | replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0755
    backup: true
  become: true
  with_fileglob:
    - templates/user_parameter/*.j2
  notify: restart-zabbix-agent

- name: Start and enable Zabbix stuff
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - zabbix-agent
  become: true
