- name: Install zabbix_api
  ansible.builtin.pip:
    state: present
    name: zabbix_api
  become: true

- name: Deploy agent auto-registration action
  community.zabbix.zabbix_action:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    name: Agent auto-registration
    event_source: auto_registration
    state: present
    status: enabled
    esc_period: 0s
    operations:
      - type: add_host

- name: Deploy Linux agent action
  community.zabbix.zabbix_action:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    name: Linux agent action
    event_source: auto_registration
    state: present
    status: enabled
    esc_period: 0s
    conditions:
      - type: host_metadata
        operator: like
        value: Linux
    operations:
      - type: link_to_template
        templates:
          - Linux by Zabbix agent
      - type: enable_host

- name: Create host groups
  community.zabbix.zabbix_group:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    state: present
    host_groups:
      - Linux servers

- name: Delete host (Zabbix server)
  community.zabbix.zabbix_host:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    state: absent
    host_name: Zabbix server

- name: Create linux host
  community.zabbix.zabbix_host:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    state: present
    host_name: "{{ item }}"
    visible_name: "{{ item }}"
    description: "{{ item }}"
    host_groups:
      - Linux servers
    link_templates:
      - Linux by Zabbix agent active
    status: enabled
  loop: "{{ linux_servers }}"
