- name: Install zabbix_api
  ansible.builtin.pip:
    state: present
    name: zabbix_api
  become: true

- name: Deploy agent auto-registration action
  community.zabbix.zabbix_action:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    name: Agent auto-registration
    event_source: auto_registration
    state: present
    status: enabled
    esc_period: 0s
    operations:
      - type: add_host

- name: Deploy Linux agent action
  community.zabbix.zabbix_action:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    name: Linux agent action
    event_source: auto_registration
    state: present
    status: enabled
    esc_period: 0s
    conditions:
      - type: host_metadata
        operator: like
        value: Linux
    operations:
      - type: link_to_template
        templates:
          - Linux by Zabbix agent
      - type: enable_host

- name: Create host groups
  community.zabbix.zabbix_group:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    state: present
    host_groups:
      - Linux servers
      - SNMP servers
      - Printers
      - Ping servers
      - UniFi devices

- name: Delete host (Zabbix server)
  community.zabbix.zabbix_host:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    state: absent
    host_name: Zabbix server

- name: Create linux host
  community.zabbix.zabbix_host:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    state: present
    host_name: "{{ item.dns }}"
    visible_name: "{{ item.dns }}"
    description: "{{ item.dns }}"
    host_groups:
      - Linux servers
    link_templates:
      - Linux by Zabbix agent active
    status: enabled
    interfaces:
      - port: "10050"
        type: agent
        dns: "{{ item.dns }}"
        ip: "{{ item.ip }}"
        main: 1
  loop: "{{ linux_servers }}"

- name: Create generic snmp host
  community.zabbix.zabbix_host:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    state: present
    host_name: "{{ item.dns }}"
    visible_name: "{{ item.dns }}"
    description: "{{ item.dns }}"
    host_groups:
      - SNMP servers
    link_templates:
      - Generic SNMP
      - Interfaces SNMP
    status: enabled
    interfaces:
      - details:
          community: public
          version: 2
        port: "161"
        type: snmp
        dns: "{{ item.dns }}"
        ip: "{{ item.ip }}"
        main: 1
  loop: "{{ snmp_servers }}"
  when:
    - snmp_servers is defined

- name: Create printer snmp host
  community.zabbix.zabbix_host:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    state: present
    host_name: "{{ item.dns }}"
    visible_name: "{{ item.dns }}"
    description: "{{ item.dns }}"
    host_groups:
      - Printers
    link_templates:
      - Generic SNMP
    status: enabled
    interfaces:
      - details:
          community: public
          version: 2
        port: "161"
        type: snmp
        dns: "{{ item.dns }}"
        ip: "{{ item.ip }}"
        main: 1
  loop: "{{ printers }}"

- name: Create ping host
  community.zabbix.zabbix_host:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    state: present
    host_name: "{{ item.dns }}"
    visible_name: "{{ item.dns }}"
    description: "{{ item.dns }}"
    host_groups:
      - Printers
    link_templates:
      - ICMP Ping
    status: enabled
    interfaces:
      - type: agent
        dns: "{{ item.dns }}"
        ip: "{{ item.ip }}"
        main: 1
        useip: 0
  loop: "{{ ping_servers }}"

- name: Create generic ping host
  community.zabbix.zabbix_host:
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    state: present
    host_name: "{{ item.dns }}"
    visible_name: "{{ item.dns }}"
    description: "{{ item.dns }}"
    host_groups:
      - UniFi devices
    link_templates:
      - ICMP Ping
    status: enabled
    interfaces:
      - type: agent
        dns: "{{ item.dns }}"
        ip: "{{ item.ip }}"
        main: 1
        useip: 0
  loop: "{{ unifi_devices }}"

# - name: Create generic snmp host
#   community.zabbix.zabbix_host:
#     server_url: "{{ server_url }}"
#     login_user: "{{ login_user }}"
#     login_password: "{{ login_password }}"
#     state: present
#     host_name: "{{ item.dns }}"
#     visible_name: "{{ item.dns }}"
#     description: "{{ item.dns }}"
#     host_groups:
#       - UniFi devices
#     link_templates:
#       - Generic SNMP
#       - Interfaces SNMP
#     status: enabled
#     interfaces:
#       - details:
#           community: public
#           version: 2
#         port: "161"
#         type: snmp
#         dns: "{{ item.dns }}"
#         ip: "{{ item.ip }}"
#         main: 1
#   loop: "{{ unifi_devices }}"
