- name: restart-opennebula-sunstone
  ansible.builtin.systemd:
    name: opennebula-sunstone
    state: restarted
  become: true

- name: restart-opennebula-flow
  ansible.builtin.systemd:
    name: opennebula-flow
    state: restarted
  become: true

- name: restart-opennebula
  ansible.builtin.systemd:
    name: opennebula
    state: restarted
  become: true
