- name: Create /etc/rc.local
  file:
    state: touch
    path: /etc/rc.local
    owner: root
    group: root
    mode: 0755
  become: yes
  changed_when: no

- name: Put shebang in /etc/rc.local
  lineinfile:
    state: present
    path: /etc/rc.local
    insertbefore: BOF
    line: '#!/usr/bin/env bash'
  become: yes

- name: Put exit 0 in /etc/rc.local
  lineinfile:
    state: present
    path: /etc/rc.local
    insertbefore: EOF
    line: 'exit 0'
  become: yes

- name: Deploy hello world json
  copy:
    dest: /var/tmp/hello-world.json
    owner: root
    group: root
    mode: 0644
    content: |
      {
        "host_config_key": "{{ lifecycle.host_config_key }}",
        "extra_vars": {
          "slack_override": {
            "channel": "{{ lifecycle.slack_channel }}",
            "msg": "> {{ inventory_hostname }} rides the :gun: again",
            "username": "Ubuntu",
            "icon_url": "https://assets.ubuntu.com/v1/29985a98-ubuntu-logo32.png"
          }
        }
      }
  become: yes

- name: Deploy hello world into /etc/rc.local
  blockinfile:
    path: /etc/rc.local
    block: |
      /usr/bin/curl -f -H 'Content-Type: application/json' -XPOST -d@/var/tmp/hello-world.json \
        https://awx.cloudmason.org:443/api/v2/job_templates/52/callback/
  become: yes

- name: Deploy goodbye cruel world json
  copy:
    dest: /var/tmp/goodbye-world.json
    owner: root
    group: root
    mode: 0644
    content: |
      {
        "host_config_key": "{{ lifecycle.host_config_key }}",
        "extra_vars": {
          "slack_override": {
            "channel": "{{ lifecycle.slack_channel }}",
            "msg": "> {{ inventory_hostname }} rebooting :crossed_fingers:",
            "username": "Ubuntu",
            "icon_url": "https://assets.ubuntu.com/v1/29985a98-ubuntu-logo32.png"
          }
        }
      }
  become: yes

- name: Deploy goodbye world into /etc/init.d/goodbye
  copy:
    dest: /etc/init.d/goodbye
    owner: root
    group: root
    mode: 0755
    content: |
      #!/bin/sh
      /usr/bin/curl -f -H 'Content-Type: application/json' -XPOST -d@/var/tmp/goodbye-world.json \
        https://awx.cloudmason.org:443/api/v2/job_templates/52/callback/
      exit 0
  become: yes

- name: Symlink goodbye into /etc/rc0.d/K99goodbye
  file:
    state: link
    force: yes
    src: /etc/init.d/goodbye
    dest: /etc/rc0.d/K99goodbye
    owner: root
    group: root
    mode: 0755
  become: yes
