---
- package:
    name: "{{ item }}"
    state: present
  loop:
    - bash-completion
    - bridge-utils
    - fail2ban
    - git
    - htop
    - libvirt-clients
    - libvirt-daemon-system
    - mailutils
    - netdata
    - postfix
    - prometheus
    - prometheus-node-exporter
    - qemu-kvm
    - screen
    - speedtest-cli
    - vim
    - virtinst

- name: deploy /etc/sysctl.d/bridge.conf
  copy:
    dest: /etc/sysctl.d/bridge.conf
    mode: 0644
    content: |
      net.bridge.bridge-nf-call-ip6tables=0
      net.bridge.bridge-nf-call-iptables=0
      net.bridge.bridge-nf-call-arptables=0
    backup: yes

- name: deploy /etc/udev/rules.d/99-bridge.rules
  copy:
    dest: /etc/udev/rules.d/99-bridge.rules
    mode: 0644
    content: |
      ACTION=="add", SUBSYSTEM=="module", KERNEL=="br_netfilter", RUN+="/sbin/sysctl -p /etc/sysctl.d/bridge.conf"
    backup: yes

- name: deploy /etc/netplan/01-network-manager-all.yaml
  copy:
    dest: /etc/netplan/01-network-manager-all.yaml
    mode: 0644
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          enp2s0:
            dhcp4: yes
        bridges:
          br0:
            dhcp4: yes
            interfaces:
              - enp2s0
    backup: yes

- name: punch a hole for stuff
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item.0 }}"
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: "{{ item.1 }}"
  with_together:
    - ['19999', '9090', '9100']
    - ['netdata', 'prometheus', 'prometheus-node-exporter']

- name: fixup /etc/netdata/netdata.conf
  copy:
    dest: /etc/netdata/netdata.conf
    content: |
      # NetData Configuration

      # The current full configuration can be retrieved from the running
      # server at the URL
      #
      #   http://localhost:19999/netdata.conf
      #
      # for example:
      #
      #   wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
      #

      [global]
        hostname = ambrosia.cloudmason.org
        run as user = netdata
        web files owner = root
        web files group = root
        # Netdata is not designed to be exposed to potentially hostile
        # networks. See https://github.com/netdata/netdata/issues/164
        bind socket to IP = 0.0.0.0
    backup: yes
  notify: restart netdata

- name: deploy /etc/fail2ban/jail.local
  copy:
    dest: /etc/fail2ban/jail.local
    mode: 0644
    content: |
      [sshd]
      enabled = true
      port = 22
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 3

- name: fail2ban cron for nginx wall of shame
  cron:
    name: fail2-ban cron
    minute: "*/5"
    user: root
    job: |
      /sbin/iptables -L f2b-sshd 2>/dev/null | grep REJECT | awk '{print $4}' >/var/www/html/f2b-sshd 2>/dev/null

- name: deploy /etc/postfix/gmail_sasl
  copy:
    dest: /etc/postfix/gmail_sasl
    mode: 0600
    content:
      !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39316133316539343231343435343363666633643563336661323633616630316639646534656436
      6130633766323763353439306365663531393734643137390a636238376563396461343962343163
      36363361653032346134643666353035666639376465393432313439323939616263353066353665
      6135323338383034650a623930353763366535336164653736303538633638396130393366306233
      63333737303639396230396331353161623539653266636637316165666365336136383662343266
      34626564613638336465373563643536646563613566306337353463666138643630626362353735
      343536353463343431363534356639373665

- name: postmap /etc/postfix/gmail_sasl
  shell:
    postmap /etc/postfix/gmail_sasl

- name: set up postfix for relay
  blockinfile:
    path: /etc/postfix/main.cf
    block: |
      relayhost = [smtp.gmail.com]:587
      smtp_sasl_auth_enable = yes
      smtp_sasl_security_options = noanonymous
      smtp_sasl_password_maps = hash:/etc/postfix/gmail_sasl
      smtp_tls_security_level = encrypt
      smtp_tls_security_level = verify
      smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

- name: deploy /etc/postfix/access
  copy:
    dest: /etc/postfix/access
    mode: 0644
    content: |
      192.168/16 OK

- name: postmap /etc/postfix/access
  shell:
    postmap /etc/postfix/access

- name: update /etc/aliases
  blockinfile:
    path: /etc/aliases
    block: |
      root: mark
      mark: mamercad@gmail.com
    backup: yes

- name: newaliases
  shell: |
    newaliases
