---

- name: Include AWX user
  include_role:
    name: awx
    tasks_from: user

- name: Include Healthchecks.io
  include_tasks:
    file: healthchecks_io.yml

- name: Include Packages
  include_tasks:
    file: packages.yml

- name: Include Mark
  include_tasks:
    file: mark.yml
