---

- name: Include mark vars
  include_vars:
    file: mark.yml
    name: mark

- name: Ensure zsh installed
  apt:
    update_cache: true
    name: zsh
    state: present
  become: true

- name: Ensure mark group exists
  group:
    state: present
    name: "{{ mark.group }}"
  become: true

- name: Ensure mark exists
  user:
    name: "{{ mark.user }}"
    comment: "{{ mark.full_name }}"
    group: "{{ mark.group }}"
    password: "{{ mark.password }}"
    create_home: true
    shell: "{{ mark.shell }}"
  become: true

- name: Create ~mark/.ssh
  file:
    state: directory
    path: "{{ mark.home }}/.ssh"
    owner: "{{ mark.user }}"
    group: "{{ mark.group }}"
    mode: 0700
  become: true

- name: Give mark passwordless sudo
  copy:
    content: "{{ mark.user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/{{ mark.user }}
    mode: 0440
  become: true

- name: Deploy ~mark/.ssh/authorized_keys
  copy:
    content: "{{ mark.ssh_authorized_keys }}"
    dest: "{{ mark.home }}/.ssh/authorized_keys"
    owner: "{{ mark.user }}"
    group: "{{ mark.group }}"
    mode: 0644
    backup: true
  become: true

- name: Deploy ~mark/.ssh/personal.key.pub
  copy:
    content: "{{ mark.ssh_public_key }}"
    dest: "{{ mark.home }}/.ssh/personal.key.pub"
    owner: "{{ mark.user }}"
    group: "{{ mark.group }}"
    mode: 0644
    backup: true
  become: true

- name: Deploy ~mark/.ssh/personal.key
  copy:
    content: "{{ mark.ssh_private_key }}"
    dest: "{{ mark.home }}/.ssh/personal.key"
    owner: "{{ mark.user }}"
    group: "{{ mark.group }}"
    mode: 0600
    backup: true
  become: true

- name: Ensure set -o vi
  blockinfile:
    state: present
    path: "{{ mark.home }}/.bashrc"
    block: |
      alias c=clear
      set -o vi
    backup: true
  become: true

- name: Create /var/mail/mark
  file:
    state: touch
    path: /var/mail/mark
    owner: "{{ mark.user }}"
    group: "{{ mark.group }}"
    mode: 0600
  changed_when: false
  become: true
