---

- name: Deploy netdata apt-key
  apt_key:
    state: present
    url: https://packagecloud.io/netdata/netdata/gpgkey
  become: yes

- name: Deploy /etc/apt/sources.list.d/netdata_netdata.list
  copy:
    dest: /etc/apt/sources.list.d/netdata_netdata.list
    owner: root
    group: root
    mode: 0644
    content: |
      deb https://packagecloud.io/netdata/netdata/ubuntu/ {{ ansible_distribution_release }} main
      deb-src https://packagecloud.io/netdata/netdata/ubuntu/ {{ ansible_distribution_release }} main
  become: yes

- name: Install netdata
  apt:
    state: present
    name: netdata
    update_cache: yes
  become: yes

- name: Start and enable netdata
  systemd:
    name: netdata
    state: started
    enabled: yes
  become: yes

- name: Claim node to the cloud
  shell: /usr/sbin/netdata-claim.sh -token=iYKPYz_qbHCwUm8Nf4qtInYWo7rHDU3EsRlAmGR-tmRON-6wJeP6eVguTEy6dBZ_4Wv7DigICkGEhc1M8K76dUE8YKJ2u15jB_iq2xsyjigpY3dIGPhkYK9luPitMz8i1Fx-PYM -rooms=f4f6285d-b7b5-4365-ac5d-3197a9b3831b -url=https://app.netdata.cloud
  become: yes
  ignore_errors: yes # Might be claimed already
