---

- name: Deploy netdata apt-key
  apt_key:
    state: present
    url: https://packagecloud.io/netdata/netdata/gpgkey
  become: yes

- name: Deploy /etc/apt/sources.list.d/netdata_netdata.list
  copy:
    dest: /etc/apt/sources.list.d/netdata_netdata.list
    owner: root
    group: root
    mode: 0644
    content: |
      deb https://packagecloud.io/netdata/netdata/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main
      deb-src https://packagecloud.io/netdata/netdata/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main
  become: yes

- name: Install netdata
  apt:
    state: present
    name: netdata
    update_cache: yes
  become: yes

- name: Deploy /etc/netdata/netdata.conf
  copy:
    owner: root
    group: root
    mode: 0644
    content: |
      # netdata configuration
      #
      # You can download the latest version of this file, using:
      #
      #  wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
      # or
      #  curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
      #
      # You can uncomment and change any of the options below.
      # The value shown in the commented settings, is the default value.
      #
      [global]
          run as user = netdata
          # the default database size - 1 hour
          history = 3600
          # some defaults to run netdata with least priority
          process scheduling policy = idle
          OOM score = 1000
      [web]
          web files owner = root
          web files group = netdata
          # by default do not expose the netdata port
          bind to = localhost
    backup: yes
  become: yes
  notify: Restart netdata

- name: Start and enable netdata
  systemd:
    name: netdata
    state: started
    enabled: yes
  become: yes

- name: Claim node to the cloud
  shell: /usr/sbin/netdata-claim.sh -token={{ netdata.netdata_claim_token }} -rooms=f4f6285d-b7b5-4365-ac5d-3197a9b3831b -url=https://app.netdata.cloud
  become: yes
  ignore_errors: yes # Might be claimed already
