---

- name: Install common packages
  apt:
    state: present
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - bash-completion
    - bridge-utils
    - curl
    - dnsutils
    - git
    - glances
    - gnupg
    - htop
    - neofetch
    - python3
    - python3-pip
    - screen
    - speedtest-cli
    - vim
  become: yes
