---

- name: Install common packages
  apt:
    state: present
    name: "{{ item }}"
  loop:
    - bash-completion
    - bridge-utils
    - git
    - glances
    - htop
    - neofetch
    - screen
    - speedtest-cli
    - vim
  become: yes
  tags: apt
