---

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest  # noqa package-latest
  become: true
  register: update
  tags: ['update', 'updates']

- name: Remove useless packages from the cache
  apt:
    autoclean: true
  become: true
  register: clean
  tags: ['update', 'updates']

- name: Remove dependencies that are no longer required
  apt:
    autoremove: true
  become: true
  register: remove
  tags: ['update', 'updates']

- name: Check if /var/run/reboot-required exists
  stat:
    path: /var/run/reboot-required
  register: reboot
  tags: ['update', 'updates']

- name: Install packages
  apt:
    state: present
    name:
      - curl
      - fd-find
      - fzf
      - git
      - mailutils
      - ncdu
      - net-tools
      - nodejs
      - pipenv
      - rbenv
      - silversearcher-ag
      - traceroute
      - vim
      - zsh
  become: true
