---

- name: Install common packages
  apt:
    state: present
    name: "{{ item }}"
  loop:
    - bash-completion
    - bridge-utils
    - git
    - glances
    - htop
    - neofetch
    - prometheus-node-exporter
    - screen
    - speedtest-cli
    - vim
  become: yes

- name: Start and enable node_exporter
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes
  become: yes
