---

- name: Install postfix stuff
  apt:
    state: present
    name: "{{ item }}"
  loop:
    - mailutils
    - postfix
  become: yes

- name: Deploy /etc/postfix/gmail_sasl
  copy:
    dest: /etc/postfix/gmail_sasl
    mode: 0600
    content: "{{ postfix.gmail_sasl }}"
  become: yes
  notify: Restart postfix

- name: Call postmap /etc/postfix/gmail_sasl
  shell:
    postmap /etc/postfix/gmail_sasl
  become: yes
  notify: Restart postfix

- name: Set up postfix for relay
  blockinfile:
    path: /etc/postfix/main.cf
    block: |
      relayhost = [smtp.gmail.com]:587
      smtp_sasl_auth_enable = yes
      smtp_sasl_security_options = noanonymous
      smtp_sasl_password_maps = hash:/etc/postfix/gmail_sasl
      smtp_tls_security_level = encrypt
      smtp_tls_security_level = verify
      smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
  become: yes
  notify: Restart postfix

- name: Deploy /etc/postfix/access
  copy:
    dest: /etc/postfix/access
    mode: 0644
    content: |
      {{ postfix.access }} OK
  become: yes
  notify: Restart postfix

- name: Call postmap /etc/postfix/access
  shell:
    postmap /etc/postfix/access
  become: yes
  notify: Restart postfix

- name: Update /etc/aliases
  blockinfile:
    path: /etc/aliases
    block: |
      root: "{{ postfix.root_to }}"
      mark: "{{ postfix.mark_to }}"
    backup: yes
  become: yes

- name: Call newaliases
  shell: |
    newaliases
  become: yes
  notify: Restart postfix

- name: Enable 587/tcp (submission)
  lineinfile:
    state: present
    path: /etc/postfix/master.cf
    line: submission inet n - y - - smtpd
    backup: yes
  become: yes
  notify: Restart postfix

- name: Start and enable postfix
  systemd:
    name: postfix
    state: started
    enabled: yes
  become: yes
