- name: Install prometheus-node-exporter
  apt:
    state: present
    name: prometheus-node-exporter
  become: true

- name: Start and enable prometheus-node-exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    started: true
    enabled: true
  become: true
