---

- name: Include mark vars
  ansible.builtin.include_vars:
    file: mark.yml
    name: mark

- name: Fetch starship install.sh
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship.sh
    mode: 0755
  become: true

- name: Install starship.sh
  ansible.builtin.shell:
    cmd: /tmp/starship.sh -y
  args:
    creates: /usr/local/bin/starship
  become: true

- name: Ensure eval starship in ~/.bashrc
  ansible.builtin.lineinfile:
    path: "{{ mark.home }}/.bashrc"
    line: eval "$(starship init bash)"
    backup: true
  become: true
  become_user: "{{ mark.user }}"
