- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  become: yes
  register: updates

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes
  register: cleans

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes
  register: removes
