---

- name: Remove openresolv
  apt:
    state: absent
    name: openresolv
  become: true

- name: Add resolvconf
  apt:
    state: absent
    name: resolvconf
  become: true

- name: Enable resolvconf
  systemd:
    name: resolvconf
    state: started
    enabled: true
  become: true

- name: Deploy /etc/dhcpcd.conf
  copy:
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: 0664
    content: |
      interface {{ ansible_default_ipv4.interface | default(network.interface) }}
      static ip_address={{ ansible_default_ipv4.address | default(ansible_host) }}/{{ ((ansible_default_ipv4.network|default(network.network)) + "/" + (ansible_default_ipv4.netmask|default(network.netmask))) | ansible.netcommon.ipaddr('prefix') }}
      static routers={{ ansible_default_ipv4.gateway | default(network.gateway) }}
      static domain_name_servers={{ ansible_default_ipv4.address | default(ansible_host) }}
      static domain_name={{ network.domain | default('localdomain') }}
      static domain_search={{ network.domain | default('localdomain') }}
    backup: true
  become: true
