---

- name: Install nginx and php-fpm
  apt:
    state: present
    name:
      - nginx
      - php-fpm
    update_cache: yes
  become: yes

- name: Set php-fpm version for x86_64 (bionic)
  set_fact:
    php_fpm_version: 7.2
  when:
    - ansible_architecture == 'x86_64'
    - ansible_distribution_release == 'bionic'

- name: Set php-fpm version for x86_64 (focal)
  set_fact:
    php_fpm_version: 7.4
  when:
    - ansible_architecture == 'x86_64'
    - ansible_distribution_release == 'focal'

- name: Set php-fpm version for x86_64
  set_fact:
    php_fpm_version: 7.3
  when: ansible_architecture == 'armv7l'

- name: Check if /etc/nginx/sites-enabled/default exists
  stat:
    path: /etc/nginx/sites-enabled/default
  register: default
  become: yes

- name: Move /etc/nginx/sites-enabled/default out of the way
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  when: default.stat.islnk is defined
  notify: Reload nginx
  become: yes

- name: Deploy /etc/nginx/conf.d/default.conf
  copy:
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    content: |
      server {
        listen *:8000 default_server;
        access_log /var/log/nginx/http.access.log combined;
        error_log /var/log/nginx/http.error.log;
        root /usr/share/nginx/html/cloudmason.org;
        index index.php index.html index.htm;
        location / {
          try_files $uri $uri/ index.php =404;
        }
        location ~ \.php$ {
          try_files $uri =404;
          fastcgi_pass unix:/run/php/php{{ php_fpm_version }}-fpm.sock;
          include /etc/nginx/fastcgi_params;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
        location /minecraft {
          autoindex on;
        }
      }
  become: yes
  notify: Reload nginx

- name: Start and enable nginx and phpX-fpm
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - php{{ php_fpm_version }}-fpm
  become: yes

- name: Create cloudmason.org base directory
  file:
    state: directory
    path: /usr/share/nginx/html/cloudmason.org
    owner: root
    group: root
    mode: 0755
  become: yes
  notify: Reload nginx

- name: Deploy cloudmason.org site
  copy:
    src: "cloudmason.org/{{ item }}"
    dest: "/usr/share/nginx/html/cloudmason.org/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  loop:
    - android-chrome-192x192.png
    - android-chrome-512x512.png
    - apple-touch-icon.png
    - favicon-16x16.png
    - favicon-32x32.png
    - favicon.ico

- name: Deploy cloudmason.org site
  template:
    src: "cloudmason.org/{{ item }}"
    dest: "/usr/share/nginx/html/cloudmason.org/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  loop:
    - README.md
    - cloudmason.php
    - graphs.php
    - keybase.txt
    - media.php
    - site.webmanifest

- name: Symlink cloudmason.php to index.php
  file:
    state: link
    src: /usr/share/nginx/html/cloudmason.org/cloudmason.php
    dest: /usr/share/nginx/html/cloudmason.org/index.php
    force: yes
  become: yes

- name: Install fping, fortune and fortunes
  apt:
    state: present
    name:
      - fping
      - fortune
      - fortunes
      - fortunes-bofh-excuses
  become: yes
