- name: install psutil (for pids, below)
  apt:
    name: python3-psutil
  become: yes
  tags: plex

- name: check if plex already running
  pids:
    name: Plex Media Server
  register: plex_pid
  tags: plex

- name: install plex
  apt:
    deb: https://downloads.plex.tv/plex-media-server-new/1.19.5.3112-b23ab3896/debian/plexmediaserver_1.19.5.3112-b23ab3896_amd64.deb
  when: plex_pid.pids | length > 0
  become: yes
  tags: plex

- name: punch a hole for plex
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '32400'
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: plex media server
  become: yes
  tags: plex

- name: create a media user and group
  user:
    name: mediaG
  become: yes
  tags: plex

- name: install sabnzbdplus
  apt:
    name: sabnzbdplus
  become: yes
  tags: plex

- name: create sabnzbd group
  group:
    name: sabnzbd

- name: create sabnzbd user
  user:
    name: sabnzbd
    group: sabnzbd
    groups: media

- name: deploy /etc/default/sabnzbdplus
  copy:
    dest: /etc/default/sabnzbdplus
    mode: 0644
    content: |
      # This file is sourced by /etc/init.d/sabnzbdplus
      #
      # When SABnzbd+ is started using the init script, the
      # --daemon option is always used, and the program is
      # started under the account of $USER, as set below.
      #
      # Each setting is marked either "required" or "optional";
      # leaving any required setting unconfigured will cause
      # the service to not start.

      # [required] user or uid of account to run the program as:
      USER=sabnzbd

      # [optional] full path to the configuration file of your choice;
      #            otherwise, the default location (in $USER's home
      #            directory) is used:
      CONFIG=

      # [optional] hostname/ip and port number to listen on:
      HOST=0.0.0.0
      PORT=20000

      # [optional] extra command line options, if any:
      EXTRAOPTS=
    backup: yes

- name: punch a hole for sabnzbd
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '20000'
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: sabnzbd
  become: yes
  tags: plex

- name: start and enable sabnzbdplus
  service:
    name: sabnzbdplus
    state: started
    enabled: yes
