all:
  hosts:
    net1:
      ansible_host: 192.168.1.10
      ansible_python_interpreter: /usr/bin/python3
    net2:
      ansible_host: 192.168.1.11
      ansible_python_interpreter: /usr/bin/python3
  vars:
    network:
      interface: eth0
      address: 192.168.1.0
      netmask: 255.255.255.0
      prefix: 24
      cidr: 192.168.1.0/24
      gateway: 192.168.1.1
      domain: cloudmason.org
  children:
    pi:
      hosts:
        net1:
        net2:
