---
- name: create collins user
  user:
    name: collins
    comment: Collins Infrastructure management for engineers
    state: present
- name: download collins
  get_url:
    url: https://github.com/tumblr/collins/releases/download/v2.2.0/collins-v2.2.0.zip
    dest: /home/collins
  become_user: collins
- name: create collins app root
  file:
    path: /home/collins/collins-v2.2.0
    state: directory
  become_user: collins
- name: extract collins
  unarchive:
    remote_src: yes
    src: /home/collins/collins-v2.2.0.zip
    dest: /home/collins/collins-v2.2.0
  become_user: collins
# - name: download typeset-activator
#   get_url:
#     url: https://downloads.typesafe.com/typesafe-activator/1.3.6/typesafe-activator-1.3.6-minimal.zip
#     dest: /home/collins
#     owner: collins
#     group: collins
#     mode: 0644
# - name: create the src directory
#   file:
#     path: /home/collins/src
#     state: directory
#     owner: collins
#     group: collins
#     mode: 0755
# - name: extract typeset-activator
#   unarchive:
#     remote_src: yes
#     src: /home/collins/typesafe-activator-1.3.6-minimal.zip 
#     dest: /home/collins/src
#   become_user: collins
# - name: clone the collins repo
#   git:
#     repo: https://github.com/tumblr/collins.git
#     dest: /home/collins/src/collins
#   become_user: collins
# - name: run the activator command
#   shell: /home/collins/src/activator-1.3.6-minimal/activator
#   args:
#     chdir: /home/collins/src
#   become_user: collins
# - name: run the compile command
#   shell: /home/collins/src/activator-1.3.6-minimal/activator
#   args:
#     chdir: /home/collins/src
#   become_user: collins
