# - name: Restart unbound
#   service:
#     name: unbound
#     state: restarted
#   become: yes

- name: Restart pdns
  systemd:
    name: pdns
    state: restarted
    daemon_reload: yes
  become: yes

- name: Restart pdns-recursor
  systemd:
    name: pdns-recursor
    state: restarted
    daemon_reload: yes
  become: yes
