- name: Install postgresql and pgpool2, et al
  apt:
    name:
      - acl
      - postgresql
      - pgpool2
      - libpq-dev
      - python3-psycopg2
    state: present
  become: yes

- name: Set listen_addresses to *
  community.general.postgresql_set:
    name: listen_addresses
    value: '*'
  become: yes
  become_user: postgres
  notify: Restart postgresql

- name: Configure replication auth
  community.general.postgresql_pg_hba:
    dest: /etc/postgresql/12/main/pg_hba.conf
    contype: host
    users: replication
    databases: replication
    source: 192.168.1.0/24
    method: md5
  become: yes
  become_user: postgres
  notify: Restart postgresql
