---
1:
  type: PTR
  value: gateway.cloudmason.org.
2:
  type: PTR
  value: cloudkey.cloudmason.org.
3:
  type: PTR
  value: cloudkey2.cloudmason.org.
8:
  type: PTR
  value: powerdns1.cloudmason.org.
9:
  type: PTR
  value: powerdns2.cloudmason.org.
10:
  type: PTR
  value: net1.cloudmason.org.
11:
  type: PTR
  value: net2.cloudmason.org.
14:
  type: PTR
  value: printer.cloudmason.org.
16:
  type: PTR
  value: ringdoorbell.cloudmason.org.
20:
  type: PTR
  value: openhab.cloudmason.org.
22:
  type: PTR
  value: rokufamilyroom.cloudmason.org.
26:
  type: PTR
  value: jonagold.cloudmason.org.
30:
  type: PTR
  value: coffeepot.cloudmason.org.
32:
  type: PTR
  value: rokubedroom.cloudmason.org.
47:
  type: PTR
  value: markxboxone.cloudmason.org.
50:
  type: PTR
  value: buddyxboxone.cloudmason.org.
51:
  type: PTR
  value: node5.cloudmason.org.
52:
  type: PTR
  value: basementlamp1.cloudmason.org.
53:
  type: PTR
  value: familyroomlamp.cloudmason.org.
55:
  type: PTR
  value: buddyrokutv.cloudmason.org.
56:
  type: PTR
  value: alexa5.cloudmason.org.
57:
  type: PTR
  value: sunfire.cloudmason.org.
58:
  type: PTR
  value: indyiphone.cloudmason.org.
60:
  type: PTR
  value: dehumidifier.cloudmason.org.
63:
  type: PTR
  value: basement.cloudmason.org.
64:
  type: PTR
  value: clusterpi2.cloudmason.org.
69:
  type: PTR
  value: roomba.cloudmason.org.
70:
  type: PTR
  value: switch3.cloudmason.org.
72:
  type: PTR
  value: juderokutv.cloudmason.org.
73:
  type: PTR
  value: honeycrisp.cloudmason.org.
74:
  type: PTR
  value: switch4.cloudmason.org.
76:
  type: PTR
  value: nest.cloudmason.org.
77:
  type: PTR
  value: judeypc.cloudmason.org.
80:
  type: PTR
  value: alexa1.cloudmason.org.
81:
  type: PTR
  value: clusterpi1.cloudmason.org.
84:
  type: PTR
  value: nintendoswitch.cloudmason.org.
85:
  type: PTR
  value: alexa2.cloudmason.org.
86:
  type: PTR
  value: streamlabs.cloudmason.org.
87:
  type: PTR
  value: plugoutside1.cloudmason.org.
88:
  type: PTR
  value: wyzeback.cloudmason.org.
89:
  type: PTR
  value: lenovo.cloudmason.org.
90:
  type: PTR
  value: marypc.cloudmason.org.
92:
  type: PTR
  value: buddyiphone.cloudmason.org.
93:
  type: PTR
  value: rokulivingroom.cloudmason.org.
95:
  type: PTR
  value: switch1.cloudmason.org.
96:
  type: PTR
  value: sense.cloudmason.org.
97:
  type: PTR
  value: buddyipad.cloudmason.org.
98:
  type: PTR
  value: plugoutside2.cloudmason.org.
99:
  type: PTR
  value: ringbridge.cloudmason.org.
100:
  type: PTR
  value: maryipad1.cloudmason.org.
103:
  type: PTR
  value: marymercado.cloudmason.org.
104:
  type: PTR
  value: wyzefront.cloudmason.org.
112:
  type: PTR
  value: smartthings.cloudmason.org.
115:
  type: PTR
  value: livingroomlamp.cloudmason.org.
116:
  type: PTR
  value: C02D6D7BMD6M.cloudmason.org.
117:
  type: PTR
  value: ooma.cloudmason.org.
118:
  type: PTR
  value: qnap1.cloudmason.org.
119:
  type: PTR
  value: qnap2.cloudmason.org.
120:
  type: PTR
  value: familyroom.cloudmason.org.
121:
  type: PTR
  value: garagedoor.cloudmason.org.
122:
  type: PTR
  value: traefik1.cloudmason.org.
124:
  type: PTR
  value: alexashow1.cloudmason.org.
125:
  type: PTR
  value: node0.cloudmason.org.
126:
  type: PTR
  value: switch2.cloudmason.org.
127:
  type: PTR
  value: pws.cloudmason.org.
128:
  type: PTR
  value: node1.cloudmason.org.
129:
  type: PTR
  value: maryiphone.cloudmason.org.
131:
  type: PTR
  value: node2.cloudmason.org.
134:
  type: PTR
  value: indyipod.cloudmason.org.
135:
  type: PTR
  value: ambrosia.cloudmason.org.
136:
  type: PTR
  value: rog.cloudmason.org.
140:
  type: PTR
  value: livingroomtv.cloudmason.org.
141:
  type: PTR
  value: bedroom.cloudmason.org.
144:
  type: PTR
  value: basementlamp2.cloudmason.org.
146:
  type: PTR
  value: maryipad2.cloudmason.org.
145:
  type: PTR
  value: node4.cloudmason.org.
148:
  type: PTR
  value: fuji.cloudmason.org.
149:
  type: PTR
  value: biaslighting.cloudmason.org.
150:
  type: PTR
  value: node3.cloudmason.org.
162:
  type: PTR
  value: marymacbook.cloudmason.org.
170:
  type: PTR
  value: awx.sunfire.cloudmason.org.
171:
  type: PTR
  value: hello-world.sunfire.cloudmason.org.
180:
  type: PTR
  value: judeipad.cloudmason.org.
187:
  type: PTR
  value: ringbasestation.cloudmason.org.
188:
  type: PTR
  value: alexa3.cloudmason.org.
221:
  type: PTR
  value: awx-web-svc.jonagold.cloudmason.org.
222:
  type: PTR
  value: prometheus.jonagold.cloudmason.org.
223:
  type: PTR
  value: grafana.jonagold.cloudmason.org.
224:
  type: PTR
  value: kiali.cloudmason.org.
