---
'':
  - type: A
    values:
      - 192.168.1.10
      - 192.168.1.11
  - type: MX
    values:
      - exchange: smtp.cloudmason.org.
        preference: 10
    ttl: 3600
gateway:
  type: A
  value: 192.168.1.1
cloudkey:
  type: A
  value: 192.168.1.2
cloudkey2:
  type: A
  value: 192.168.1.3
powerdns1:
  type: A
  value: 192.168.1.8
powerdns2:
  type: A
  value: 192.168.1.9
dns:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
mail:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
smtp:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
www:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
web:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
net1:
  type: A
  value: 192.168.1.10
net2:
  type: A
  value: 192.168.1.11
printer:
  type: A
  value: 192.168.1.14
ringdoorbell:
  type: A
  value: 192.168.1.16
openhab:
  type: A
  value: 192.168.1.20
rokufamilyroom:
  type: A
  value: 192.168.1.22
jonagold:
  type: A
  value: 192.168.1.26
coffeepot:
  type: A
  value: 192.168.1.30
rokubedroom:
  type: A
  value: 192.168.1.32
markxboxone:
  type: A
  value: 192.168.1.47
buddyxboxone:
  type: A
  value: 192.168.1.50
node5:
  type: A
  value: 192.168.1.51
basementlamp1:
  type: A
  value: 192.168.1.52
familyroomlamp:
  type: A
  value: 192.168.1.53
buddyrokutv:
  type: A
  value: 192.168.1.55
alexa5:
  type: A
  value: 192.168.1.56
sunfire:
  type: A
  value: 192.168.1.57
dehumidifier:
  type: A
  value: 192.168.1.60
basement:
  type: A
  value: 192.168.1.63
roomba:
  type: A
  value: 192.168.1.69
switch3:
  type: A
  value: 192.168.1.70
honeycrisp:
  type: A
  value: 192.168.1.73
nest:
  type: A
  value: 192.168.1.76
judeypc:
  type: A
  value: 192.168.1.77
alexa1:
  type: A
  value: 192.168.1.80
nintendoswitch:
  type: A
  value: 192.168.1.84
alexa2:
  type: A
  value: 192.168.1.85
streamlabs:
  type: A
  value: 192.168.1.86
plugoutside1:
  type: A
  value: 192.168.1.87
lenovo:
  type: A
  value: 192.168.1.89
marypc:
  type: A
  value: 192.168.1.90
buddyiphone:
  type: A
  value: 192.168.1.92
rokulivingroom:
  type: A
  value: 192.168.1.93
switch1:
  type: A
  value: 192.168.1.95
sense:
  type: A
  value: 192.168.1.96
buddyipad:
  type: A
  value: 192.168.1.97
plugoutside2:
  type: A
  value: 192.168.1.98
ringbridge:
  type: A
  value: 192.168.1.99
maryipad:
  type: A
  value: 192.168.1.100
marymercado:
  type: A
  value: 192.168.1.103
smartthings:
  type: A
  value: 192.168.1.112
livingroomlamp:
  type: A
  value: 192.168.1.115
C02D6D7BMD6M:
  type: A
  value: 192.168.1.116
ooma:
  type: A
  value: 192.168.1.117
qnap:
  type: A
  values:
    - 192.168.1.118
    - 192.168.1.119
qnap1:
  type: A
  value: 192.168.1.118
qnap2:
  type: A
  value: 192.168.1.119
familyroom:
  type: A
  value: 192.168.1.120
garagedoor:
  type: A
  value: 192.168.1.121
traefik1:
  type: A
  value: 192.168.1.122
alexashow1:
  type: A
  value: 192.168.1.124
node0:
  type: A
  value: 192.168.1.125
switch2:
  type: A
  value: 192.168.1.126
pws:
  type: A
  value: 192.168.1.127
node1:
  type: A
  value: 192.168.1.128
maryiphone:
  type: A
  value: 192.168.1.129
node2:
  type: A
  value: 192.168.1.131
ambrosia:
  type: A
  value: 192.168.1.135
rog:
  type: A
  value: 192.168.1.136
livingroomtv:
  type: A
  value: 192.168.1.140
bedroom:
  type: A
  value: 192.168.1.141
basementlamp2:
  type: A
  value: 192.168.1.144
node4:
  type: A
  value: 192.168.1.145
fuji:
  type: A
  value: 192.168.1.148
biaslighting:
  type: A
  value: 192.168.1.149
node3:
  type: A
  value: 192.168.1.150
marymacbook:
  type: A
  value: 192.168.1.162
hello-world.sunfire:
  type: A
  value: 192.168.1.171
judeipad:
  type: A
  value: 192.168.1.180
ringbasestation:
  type: A
  value: 192.168.1.187
alexa3:
  type: A
  value: 192.168.1.188
awx:
  type: A
  value: 192.168.1.221
prometheus:
  type: A
  value: 192.168.1.222
grafana:
  type: A
  value: 192.168.1.223
kiali:
  type: A
  value: 192.168.1.224
