---
'':
  - type: A
    values:
      - 192.168.1.10
      - 192.168.1.11
  - type: MX
    values:
      - exchange: smtp.cloudmason.org.
        preference: 10
    ttl: 3600
gateway:
  type: A
  value: 192.168.1.1
# cloudkey:
#   type: A
#   value: 192.168.1.2
cloudkey:
  type: A
  value: 192.168.1.3
unifi:
  type: CNAME
  value: cloudkey.cloudmason.org.
net5:
  type: A
  value: 192.168.1.8
net6:
  type: A
  value: 192.168.1.9
minecraft:
  type: CNAME
  value: lenovo.cloudmason.org.
awx:
  type: CNAME
  value: net.cloudmason.org.
awx-dev:
  type: CNAME
  value: net.cloudmason.org.
concourse:
  type: CNAME
  value: net.cloudmason.org.
docker:
  type: CNAME
  value: net.cloudmason.org.
grafana:
  type: CNAME
  value: net.cloudmason.org.
prometheus:
  type: CNAME
  value: net.cloudmason.org.
nzbget:
  type: CNAME
  value: net.cloudmason.org.
sonarr:
  type: CNAME
  value: net.cloudmason.org.
radarr:
  type: CNAME
  value: net.cloudmason.org.
net:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
dns:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
mail:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
smtp:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
www:
  type: CNAME
  value: net.cloudmason.org.
web:
  type: CNAME
  value: net.cloudmason.org.
net1:
  type: A
  value: 192.168.1.10
net2:
  type: A
  value: 192.168.1.11
net3:
  type: A
  value: 192.168.1.12
net4:
  type: A
  value: 192.168.1.13
printer:
  type: A
  value: 192.168.1.14
ringdoorbell:
  type: A
  value: 192.168.1.16
openhab:
  type: A
  value: 192.168.1.20
rokufamilyroom:
  type: A
  value: 192.168.1.22
cloudkeyfallback:
  type: A
  value: 192.168.1.30
coffeepot:
  type: A
  value: 192.168.1.31
rokubedroom:
  type: A
  value: 192.168.1.32
ringbasestation:
  type: A
  value: 192.168.1.33
jonagold:
  type: A
  value: 192.168.1.43
markxboxone:
  type: A
  value: 192.168.1.47
buddyxboxone:
  type: A
  value: 192.168.1.50
node5:
  type: A
  value: 192.168.1.51
basementlamp1:
  type: A
  value: 192.168.1.52
db1:
  type: A
  value: 192.168.1.53
buddyrokutv:
  type: A
  value: 192.168.1.55
alexa5:
  type: A
  value: 192.168.1.56
sunfire:
  type: A
  value: 192.168.1.57
indiphone:
  type: A
  value: 192.168.1.58
dehumidifier:
  type: A
  value: 192.168.1.60
clusterpi0:
  type: A
  value: 192.168.1.62
basement:
  type: A
  value: 192.168.1.63
clusterpi2:
  type: A
  value: 192.168.1.64
clusterpi4:
  type: A
  value: 192.168.1.66
clusterpi5:
  type: A
  value: 192.168.1.68
roomba:
  type: A
  value: 192.168.1.69
switch3:
  type: A
  value: 192.168.1.70
judexboxx:
  type: A
  value: 192.168.1.71
juderokutv:
  type: A
  value: 192.168.1.72
honeycrisp:
  type: A
  value: 192.168.1.73
switch4:
  type: A
  value: 192.168.1.74
judeair:
  type: A
  value: 192.168.1.75
nest:
  type: A
  value: 192.168.1.76
judeypc:
  type: A
  value: 192.168.1.77
alexa1:
  type: A
  value: 192.168.1.80
clusterpi1:
  type: A
  value: 192.168.1.81
nintendoswitch:
  type: A
  value: 192.168.1.84
alexa2:
  type: A
  value: 192.168.1.85
streamlabs:
  type: A
  value: 192.168.1.86
plugoutside1:
  type: A
  value: 192.168.1.87
wyzeback:
  type: A
  value: 192.168.1.88
lenovo:
  type: A
  value: 192.168.1.89
marypcwifi:
  type: A
  value: 192.168.1.90
ambrosia:
  type: A
  value: 192.168.1.91
buddyiphone:
  type: A
  value: 192.168.1.92
rokulivingroom:
  type: A
  value: 192.168.1.93
judeswitch:
  type: A
  value: 192.168.1.94
switch1:
  type: A
  value: 192.168.1.95
sense:
  type: A
  value: 192.168.1.96
buddyipad:
  type: A
  value: 192.168.1.97
plugoutside2:
  type: A
  value: 192.168.1.98
ringbridge:
  type: A
  value: 192.168.1.99
maryipad1:
  type: A
  value: 192.168.1.100
buddyxboxx:
  type: A
  value: 192.168.1.101
rog-wifi:
  type: A
  value: 192.168.1.102
marymercado:
  type: A
  value: 192.168.1.103
wyzefront:
  type: A
  value: 192.168.1.104
retroarcade:
  type: A
  value: 192.168.1.105
marypc:
  type: A
  value: 192.168.1.106
db2:
  type: A
  value: 192.168.1.107
gala:
  type: A
  value: 192.168.1.109
clusterpi6:
  type: A
  value: 192.168.1.111
livingroomlamp:
  type: A
  value: 192.168.1.115
clusterpi3:
  type: A
  value: 192.168.1.116
ooma:
  type: A
  value: 192.168.1.117
qnap:
  type: A
  values:
    - 192.168.1.118
    - 192.168.1.119
qnap1:
  type: A
  value: 192.168.1.118
qnap2:
  type: A
  value: 192.168.1.119
familyroom:
  type: A
  value: 192.168.1.120
garagedoor:
  type: A
  value: 192.168.1.121
traefik1:
  type: A
  value: 192.168.1.122
alexashow1:
  type: A
smartthings:
  type: A
  value: 192.168.1.112
livingroomlamp:
  type: A
  value: 192.168.1.115
C02D6D7BMD6M:
  type: A
  value: 192.168.1.116
ooma:
  type: A
  value: 192.168.1.117
qnap:
  type: A
  values:
    - 192.168.1.118
    - 192.168.1.119
qnap1:
  type: A
  value: 192.168.1.118
qnap2:
  type: A
  value: 192.168.1.119
familyroom:
  type: A
  value: 192.168.1.120
garagedoor:
  type: A
  value: 192.168.1.121
traefik1:
  type: A
  value: 192.168.1.122
alexashow1:
  type: A
  value: 192.168.1.124
node0:
  type: A
  value: 192.168.1.125
switch2:
  type: A
  value: 192.168.1.126
pws:
  type: A
  value: 192.168.1.127
node1:
  type: A
  value: 192.168.1.128
maryiphone:
  type: A
  value: 192.168.1.129
node2:
  type: A
  value: 192.168.1.131
markapplewatch:
  type: A
  value: 192.168.1.133
indyipod:
  type: A
  value: 192.168.1.134
rog:
  type: A
  value: 192.168.1.136
db3:
  type: A
  value: 192.168.1.137
alexa3:
  type: A
  value: 192.168.1.138
thinkpad:
  type: A
  value: 192.168.1.139
livingroomtv:
  type: A
  value: 192.168.1.140
bedroom:
  type: A
  value: 192.168.1.141
basementlamp2:
  type: A
  value: 192.168.1.144
node4:
  type: A
  value: 192.168.1.145
maryipad2:
  type: A
  value: 192.168.1.146
fuji:
  type: A
  value: 192.168.1.148
biaslighting:
  type: A
  value: 192.168.1.149
node3:
  type: A
  value: 192.168.1.150
marymacbook:
  type: A
  value: 192.168.1.162
traefik.sunfire:
  type: A
  value: 192.168.1.170
awx.sunfire:
  type: CNAME
  value: traefik.sunfire.cloudmason.org.
consul.sunfire:
  type: A
  value: 192.168.1.172
awx-service.sunfire:
  type: A
  value: 192.168.1.173
prometheus.sunfire:
  type: A
  value: 192.168.1.174
grafana.sunfire:
  type: A
  value: 192.168.1.175
alertmanager.sunfire:
  type: A
  value: 192.168.1.176
judeipad:
  type: A
  value: 192.168.1.180
awx-web-svc.jonagold:
  type: A
  value: 192.168.1.221
prometheus.jonagold:
  type: A
  value: 192.168.1.222
grafana.jonagold:
  type: A
  value: 192.168.1.223
kiali:
  type: A
  value: 192.168.1.224
concourse.lenovo:
  type: A
  value: 192.168.1.240
docker.lenovo:
  type: A
  value: 192.168.1.241
awx.lenovo:
  type: A
  value: 192.168.1.242
vault.lenovo:
  type: A
  value: 192.168.1.243
