---
'':
  type: A
  value: 192.168.1.89
gateway:
  type: A
  value: 192.168.1.1
cloudkey:
  type: A
  value: 192.168.1.2
powerdns1:
  type: A
  value: 192.168.1.8
powerdns2:
  type: A
  value: 192.168.1.9
smtp:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
www:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
web:
  type: A
  values:
    - 192.168.1.10
    - 192.168.1.11
net1:
  type: A
  value: 192.168.1.10
net2:
  type: A
  value: 192.168.1.11
printer:
  type: A
  value: 192.168.1.14
ringdoorbell:
  type: A
  value: 192.168.1.16
openhab:
  type: A
  value: 192.168.1.20
rokufamilyroom:
  type: A
  value: 192.168.1.22
jonagold:
  type: A
  value: 192.168.1.26
coffeepot:
  type: A
  value: 192.168.1.30
rokubedroom:
  type: A
  value: 192.168.1.32
basementlamp1:
  type: A
  value: 192.168.1.52
familyroomlamp:
  type: A
  value: 192.168.1.53
buddyrokutv:
  type: A
  value: 192.168.1.55
alexa5:
  type: A
  value: 192.168.1.56
dehumidifier:
  type: A
  value: 192.168.1.60
basement:
  type: A
  value: 192.168.1.63
roomba:
  type: A
  value: 192.168.1.69
switch3:
  type: A
  value: 192.168.1.70
honeycrisp:
  type: A
  value: 192.168.1.73
nest:
  type: A
  value: 192.168.1.76
judeypc:
  type: A
  value: 192.168.1.77
alexa1:
  type: A
  value: 192.168.1.80
alexa2:
  type: A
  value: 192.168.1.85
streamlabs:
  type: A
  value: 192.168.1.86
lenovo:
  type: A
  value: 192.168.1.89
marypc:
  type: A
  value: 192.168.1.90
rokulivingroom:
  type: A
  value: 192.168.1.93
switch1:
  type: A
  value: 192.168.1.95
sense:
  type: A
  value: 192.168.1.96
buddyipad:
  type: A
  value: 192.168.1.97
ringbridge:
  type: A
  value: 192.168.1.99
marymercado:
  type: A
  value: 192.168.1.103
smartthings:
  type: A
  value: 192.168.1.112
livingroomlamp:
  type: A
  value: 192.168.1.115
C02D6D7BMD6M:
  type: A
  value: 192.168.1.116
ooma:
  type: A
  value: 192.168.1.117
qnap:
  type: A
  values:
    - 192.168.1.118
    - 192.168.1.119
familyroom:
  type: A
  value: 192.168.1.120
garagedoor:
  type: A
  value: 192.168.1.121
traefik1:
  type: A
  value: 192.168.1.122
switch2:
  type: A
  value: 192.168.1.126
pws:
  type: A
  value: 192.168.1.127
maryiphone:
  type: A
  value: 192.168.1.129
ambrosia:
  type: A
  value: 192.168.1.135
rog:
  type: A
  value: 192.168.1.136
livingroomtv:
  type: A
  value: 192.168.1.140
bedroom:
  type: A
  value: 192.168.1.141
basementlamp2:
  type: A
  value: 192.168.1.144
fuji:
  type: A
  value: 192.168.1.148
biaslighting:
  type: A
  value: 192.168.1.149
marymacbook:
  type: A
  value: 192.168.1.162
ringbasestation:
  type: A
  value: 192.168.1.187
alexa3:
  type: A
  value: 192.168.1.188
awx:
  type: A
  value: 192.168.1.221
prometheus:
  type: A
  value: 192.168.1.222
grafana:
  type: A
  value: 192.168.1.223
kiali:
  type: A
  value: 192.168.1.224
