---
collections:
  - name: awx.awx
    version: 19.1.0
  - name: community.crypto
    version: 1.9.5
  - name: community.digitalocean
    version: 1.14.0
  - name: community.general
    version: 4.2.0
  - name: kubernetes.core
    version: 2.2.2
