- name: Add grafana apt key
  ansible.builtin.apt_key:
    state: present
    url: https://packages.grafana.com/gpg.key
  become: true

- name: Add grafana deb repository
  ansible.builtin.apt_repository:
    state: present
    repo: deb https://packages.grafana.com/oss/deb stable main
  become: true

- name: Install grafana
  ansible.builtin.apt:
    state: present
    name: grafana
    update_cache: true
  become: true

- name: Start and enable grafana
  ansible.builtin.systemd:
    name: grafana
    state: started
    enabled: true
  become: true
