---

- name: Download Chef Server Core
  get_url:
    url: https://packages.chef.io/files/stable/chef-server/13.2.0/ubuntu/18.04/chef-server-core_13.2.0-1_amd64.deb
    checksum: sha256:c80d63471e173188f656ff36e74afbbc97524f764f3a41cdcc51bd4fedc659a8
    dest: /tmp/chef-server-core_13.2.0-1_amd64.deb
  become: yes

- name: Install Chef Server Core
  apt:
    deb: /tmp/chef-server-core_13.2.0-1_amd64.deb
  become: yes

- name: Bootstrap Chef Server Core
  shell: |
    chef-server-ctl reconfigure --chef-license=accept
  become: yes

- name: Create a Chef Admin (mark)
  shell: |
    chef-server-ctl user-create mark Mark Mercado mamercad@gmail.com password --filename /home/mark/chef-mark.pem
  args:
    creates: /home/mark/chef-mark.pem
  become: yes

- name: Create a Chef Organization (cloudmason)
  shell: |
    chef-server-ctl org-create cloudmason Cloudmason --association_user mark --filename /home/mark/chef-cloudmason-validator.pem
  args:
    creates: /home/mark/chef-cloudmason-validator.pem
  become: yes
