---

- name: AWX Configuration
  hosts: localhost
  tasks:
    - name: awx
      include_role:
        name: awx
        tasks_from: configuration.yml
  tags: configuration

- name: AWX Service Account
  hosts: linux
  tasks:
    - name: awx
      include_role:
        name: awx
        tasks_from: service_account.yml
  tags:
    - service_account
    - account
