---
- name: Check DNS
  hosts: all
  gather_facts: no
  become: no

  vars:
    records: "{{ dns_checks }}"

  tasks:

    - name: Check
      command: |
        dig @{{ item.0 }} +short {{ item.1 }}
      register: foo
      with_nested:
        - "{{ network.dns.nameservers }}"
        - "{{ records }}"
      changed_when: no # Don't care

    - name: Debug
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ foo.results }}"
      failed_when: item.stdout == ''
