---
- name: Slack
  hosts: all
  gather_facts: no

  tasks:

    - uri:
        url: http://prometheus.jonagold.cloudmason.org:9090/api/v1/query
        method: POST
        body: 'query=sum(increase(awx_status_total{status="failed"}[1d]))'
        body_format: form-urlencoded
        return_content: yes
      register: failed

    - set_fact:
        failed_jobs: "{{ (failed.json.data.result.0.value.1 | default(0)) | float | round(1, 'ceil') | int }}"

    - uri:
        url: http://prometheus.jonagold.cloudmason.org:9090/api/v1/query
        method: POST
        body: 'query=sum(increase(awx_status_total{status="successful"}[1d]))'
        body_format: form-urlencoded
        return_content: yes
      register: successful

    - set_fact:
        successful_jobs: "{{ (successful.json.data.result.0.value.1 | default(0)) | float | round(1, 'ceil') | int }}"

    - set_fact:
        slack_merged: "{{ slack | combine(slack_override|default({})) }}"

    - set_fact:
        success_rate: "{{ ( 100.0 * successful_jobs|float / ( successful_jobs|int + failed_jobs|int) ) | round(2) }}"

    - name: Send notification message via Slack
      community.general.slack:
        token: "{{ slack_merged.ansible.token }}"
        channel: "{{ slack_merged.channel }}"
        username: "{{ slack_merged.username }}"
        icon_url: "{{ slack_merged.icon_url }}"
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "```There were {{ failed_jobs }} failed and {{ successful_jobs }} successful AWX jobs today ({{ success_rate }}%)```"
