---
- name: Slack
  hosts: all
  gather_facts: no

  tasks:

    - name: Install prereqs
      apt:
        name:
          - fortune
          - fortunes
          - fortunes-bofh-excuses

    - shell: fortune bofh-excuses linuxcookie computers linux
      register: fortune

    - set_fact:
        slack_merged: "{{ slack | combine(slack_override|default({})) }}"

    - name: Send notification message via Slack
      community.general.slack:
        token: "{{ slack_merged.ansible.token }}"
        channel: "{{ slack_merged.channel }}"
        username: "{{ slack_merged.username }}"
        icon_url: "{{ slack_merged.icon_url }}"
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "```{{ fortune.stdout_lines | join('\n') }}```"
