---
- name: ensure mark exists
  user:
    name: "{{ user }}"
    comment: "{{ full_name }}"
- name: deploy ~mark/.ssh/authorized_keys
  copy:
    content: |
      ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAirA5p3ABC+MQqE1bJkA83SHUkVBoiuaZyYRMB7up+6NW/9bSxMp36o2eFu+jFYh6O5K74Kp6yDPl+FUCXkpdmRHiEmKp6ET5+1LYc93CgWp1kieTDUVoM3e5IOmBvJrwFn/ot3ghQciO7jM34/r6j6LpDTVEXxtC0tT4SL+gXWhoWe9/McS0ElDkw0Eq7khyws6TXbSzIxNghtW+WzEFW+DYHVXRsTqhOI3AcQW4uQ8FLd5/qEvDRBZxsleTU1LUNNq99nuWpwvpRBwyAYWKkvDDz8bKj98ciqvjFShF3IUPGxrKVhgzKEN5GORTeZgQG+qQrv0AiIYyXsF+EFkOEQ== rsa-key-20180113 
    dest: "{{ home }}/.ssh/authorized_keys"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
- name: deploy ~mark/.ssh/mamercad.key.pub
  copy:
    content: |
      ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAirA5p3ABC+MQqE1bJkA83SHUkVBoiuaZyYRMB7up+6NW/9bSxMp36o2eFu+jFYh6O5K74Kp6yDPl+FUCXkpdmRHiEmKp6ET5+1LYc93CgWp1kieTDUVoM3e5IOmBvJrwFn/ot3ghQciO7jM34/r6j6LpDTVEXxtC0tT4SL+gXWhoWe9/McS0ElDkw0Eq7khyws6TXbSzIxNghtW+WzEFW+DYHVXRsTqhOI3AcQW4uQ8FLd5/qEvDRBZxsleTU1LUNNq99nuWpwvpRBwyAYWKkvDDz8bKj98ciqvjFShF3IUPGxrKVhgzKEN5GORTeZgQG+qQrv0AiIYyXsF+EFkOEQ== rsa-key-20180113
    dest: "{{ home }}/.ssh/mamercad.key.pub"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0444
- name: deploy ~mark/.ssh/mamercad.key
  copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ home }}/.ssh/mamercad.key"
    owner: "{{ user }}"
    group: "{{ group }}"
- name: deploy ~mark/.dotfile
  template:
    src: templates/{{ item }}.j2
    dest: "{{ home }}/.{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  with_items:
    - bash_profile
    - inputrc
    - gitconfig
    - gitignores
    - muttrc
    - screenrc
    - tmux.conf
    - vimrc
    - xbindkeysrc
    - xinitrc
    - zshrc
- name: clone ohmyzsh/ohmyzsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ home }}/.oh-my-zsh"
    version: master
- name: clone gpakosz/tmux
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: "{{ home }}/.tmux"
    version: master
