---
- name: ensure mark exists
  user:
    name: mark
    comment: Mark Mercado
- name: deploy ~mark/.ssh/authorized_keys
  copy:
    content: |
      ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAirA5p3ABC+MQqE1bJkA83SHUkVBoiuaZyYRMB7up+6NW/9bSxMp36o2eFu+jFYh6O5K74Kp6yDPl+FUCXkpdmRHiEmKp6ET5+1LYc93CgWp1kieTDUVoM3e5IOmBvJrwFn/ot3ghQciO7jM34/r6j6LpDTVEXxtC0tT4SL+gXWhoWe9/McS0ElDkw0Eq7khyws6TXbSzIxNghtW+WzEFW+DYHVXRsTqhOI3AcQW4uQ8FLd5/qEvDRBZxsleTU1LUNNq99nuWpwvpRBwyAYWKkvDDz8bKj98ciqvjFShF3IUPGxrKVhgzKEN5GORTeZgQG+qQrv0AiIYyXsF+EFkOEQ== rsa-key-20180113 
    dest: "{{ home }}/.ssh/authorized_keys"
    owner: mark
    group: "{{ group }}"
    mode: 0644
- name: deploy ~mark/.ssh/mamercad.key.pub
  copy:
    content: |
      ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAirA5p3ABC+MQqE1bJkA83SHUkVBoiuaZyYRMB7up+6NW/9bSxMp36o2eFu+jFYh6O5K74Kp6yDPl+FUCXkpdmRHiEmKp6ET5+1LYc93CgWp1kieTDUVoM3e5IOmBvJrwFn/ot3ghQciO7jM34/r6j6LpDTVEXxtC0tT4SL+gXWhoWe9/McS0ElDkw0Eq7khyws6TXbSzIxNghtW+WzEFW+DYHVXRsTqhOI3AcQW4uQ8FLd5/qEvDRBZxsleTU1LUNNq99nuWpwvpRBwyAYWKkvDDz8bKj98ciqvjFShF3IUPGxrKVhgzKEN5GORTeZgQG+qQrv0AiIYyXsF+EFkOEQ== rsa-key-20180113
    dest: "{{ home }}/.ssh/mamercad.key.pub"
    owner: mark
    group: "{{ group }}"
    mode: 0444
- name: deploy ~mark/.ssh/mamercad.key
  copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ home }}/.ssh/mamercad.key"
    owner: mark
    group: "{{ group }}"
    mode: 0400
- name: deploy ~mark/.bash_profile
  template:
    src: templates/bash_profile.j2
    dest: "{{ home }}/.bash_profile"
    owner: mark
    group: "{{ group }}"
    mode: 0644
- name: deploy ~mark/.vimrc
  template:
    src: templates/vimrc.j2
    dest: "{{ home }}/.vimrc"
    owner: mark
    group: "{{ group }}"
    mode: 0644
