---

- name: Create additional Prometheus scrape_config
  copy:
    dest: /tmp/prometheus-additional.yaml
    content: |
      - job_name: "prometheus"
        static_configs:
          - targets: ["lenovo.cloudmason.org:9100"]
          - targets: ["net1.cloudmason.org:9100"]
          - targets: ["net2.cloudmason.org:9100"]
          - targets: ["powerdns1.cloudmason.org:9100"]
          - targets: ["powerdns2.cloudmason.org:9100"]
          - targets: ["qnap.cloudmason.org:9100"]
          - targets: ["sunfire.cloudmason.org:9100"]
      - job_name: "powerdns"
        static_configs:
          - targets: ["net1.cloudmason.org:8082"]
          - targets: ["net2.cloudmason.org:8082"]
        basic_auth:
          username: unused
          password: {{ powerdns_web_password }}
  vars:
    powerdns_web_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38323861346364316265643131373331363461363137316336613264643231333531633936343366
      3533303564313432313935653831636630396434336465310a636533343333613463613236626533
      30393966326461323733323331656665363735336165643661313864323432366664343836616133
      3536333966373238330a636461366137363336643134336330663938326333643064386131323464
      3638
# TODO: This is terrible
- name: Create a Kube secret out of ^
  shell: |
    kubectl -n monitoring delete secret additional-scrape-configs;
    kubectl -n monitoring create secret generic additional-scrape-configs --from-file=/tmp/prometheus-additional.yaml -o yaml;
  register: additional_scrape_config

- debug:
    var: additional_scrape_config
