- community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: awx

- community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        creationTimestamp: null
        name: awx-operator
      rules:
        - apiGroups:
            - route.openshift.io
          resources:
            - routes
          verbs:
            - '*'
        - apiGroups:
            - ""
          resources:
            - pods
            - services
            - services/finalizers
            - endpoints
            - persistentvolumeclaims
            - events
            - configmaps
            - secrets
          verbs:
            - '*'
        - apiGroups:
            - apps
            - extensions
          resources:
            - deployments
            - daemonsets
            - replicasets
            - statefulsets
            - ingresses
          verbs:
            - '*'
        - apiGroups:
            - monitoring.coreos.com
          resources:
            - servicemonitors
          verbs:
            - get
            - create
        - apiGroups:
            - apps
          resourceNames:
            - awx-operator
          resources:
            - deployments/finalizers
          verbs:
            - update
        - apiGroups:
            - ""
          resources:
            - pods/exec
          verbs:
            - create
            - get
        - apiGroups:
            - apps
          resources:
            - replicasets
          verbs:
            - get
        - apiGroups:
            - awx.ansible.com
          resources:
            - '*'
          verbs:
            - '*'

- community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: awx-operator
      subjects:
        - kind: ServiceAccount
          name: awx-operator
          namespace: awx
      roleRef:
        kind: ClusterRole
        name: awx-operator
        apiGroup: rbac.authorization.k8s.io

- community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: awx-operator
        namespace: awx

- community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: awx-operator
        namespace: awx
      spec:
        replicas: 1
        selector:
          matchLabels:
            name: awx-operator
        template:
          metadata:
            labels:
              name: awx-operator
          spec:
            serviceAccountName: awx-operator
            containers:
              - name: ansible
                command:
                  - /usr/local/bin/ao-logs
                  - /tmp/ansible-operator/runner
                  - stdout
                image: "ansible/awx-operator:0.5.0"
                imagePullPolicy: "Always"
                volumeMounts:
                  - mountPath: /tmp/ansible-operator/runner
                    name: runner
                    readOnly: true
              - name: operator
                image: "ansible/awx-operator:0.5.0"
                imagePullPolicy: "Always"
                volumeMounts:
                  - mountPath: /tmp/ansible-operator/runner
                    name: runner
                env:
                  # Watch all namespaces (cluster-scoped).
                  - name: WATCH_NAMESPACE
                    value: ""
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  - name: OPERATOR_NAME
                    value: awx-operator
            volumes:
              - name: runner
                emptyDir: {}

- community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: awxs.awx.ansible.com
      spec:
        group: awx.ansible.com
        names:
          kind: AWX
          listKind: AWXList
          plural: awxs
          singular: awx
        scope: Namespaced
        subresources:
          status: {}
        version: v1beta1
        versions:
          - name: v1beta1
            served: true
            storage: true
        validation:
          openAPIV3Schema:
            description: Schema validation for the AWX CRD
            type: object
            properties:
              spec:
                type: object
                properties:
                  deployment_type:
                    type: string
                    pattern: "^(tower|awx)(-)?.*$"
                  external_database:
                    type: boolean
                    description: |
                      If true you must supply a secret containing the location and credentials for
                      connecting to the external database by a user who has permission to create
                      and apply a schema.

                      The secret should have the name: <custom resource name>-postgres-configuration and
                      should look like:

                      apiVersion: v1
                      kind: Secret
                      metadata:
                        name: <crname>-postgres-configuration
                        namespace: <target namespace>
                      stringData:
                        host: <external ip or url resolvable by the cluster>
                        port: <external port, this usually defaults to 5432>
                        database: <desired database name>
                        username: <username to connect as>
                        password: <password to connect with>
                      type: Opaque
                required:
                  - deployment_type

- community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx
        namespace: awx
      spec:
        deployment_type: awx
        tower_admin_user: "{{ tower_admin_user }}"
        tower_admin_email: "{{ tower_admin_email }}"
        tower_admin_password: "{{ tower_admin_password }}"
        tower_broadcast_websocket_secret: "{{ tower_broadcast_websocket_secret }}"
  vars:
    tower_admin_user: admin
    tower_admin_email: root@cloudmason.org
    tower_admin_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33376261383636303039343836343865313961643435353837343265393331643233366264313735
      6161363863666666316463643166333033346165656661360a306661383465323566366239376138
      37313865623533376264373139613233373233346533633266633730343134383933313063633032
      3966623162323638340a306531363236333465656266646236616463356164333136633132383061
      3235
    tower_broadcast_websocket_secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66613437363636626234646136353231353039343864366261393936346430323639643362663866
      3530313734316638313262383039616339626233366537390a636139653335303666613733323635
      33336364336630376263333934316331653735383336376136396232366163363637333963316432
      3739303039343466300a323265363031626264353630353335336231386465313862383437633663
      3033
