- name: Create consul Namespace
  community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: consul

- name: Create consul Secret
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: consul
        namespace: consul
      type: Opaque
      data:
        gossip-encryption-key: "{{ consul.gossip_encryption_key | b64encode }}"
        ca.pem: "{{ consul.ca_pem | b64encode }}"
        consul.pem: "{{ consul.consul_pem | b64encode }}"
        consul-key.pem: "{{ consul.consul_key_pem | b64encode }}"

- name: Create consul Service
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: consul
        namespace: consul
        labels:
          name: consul
      spec:
        clusterIP: None
        selector:
          app: consul
        ports:
          - name: http
            port: 8500
            targetPort: 8500
          - name: https
            port: 8443
            targetPort: 8443
          - name: rpc
            port: 8400
            targetPort: 8400
          - name: serflan-tcp
            protocol: "TCP"
            port: 8301
            targetPort: 8301
          - name: serflan-udp
            protocol: "UDP"
            port: 8301
            targetPort: 8301
          - name: serfwan-tcp
            protocol: "TCP"
            port: 8302
            targetPort: 8302
          - name: serfwan-udp
            protocol: "UDP"
            port: 8302
            targetPort: 8302
          - name: server
            port: 8300
            targetPort: 8300
          - name: consuldns
            port: 8600
            targetPort: 8600

- name: Create consul-api Service
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: consul-api
        namespace: consul
        labels:
          name: consul
      spec:
        type: LoadBalancer
        selector:
          app: consul
        ports:
          - name: http
            port: 8500
            targetPort: 8500

- name: Create consul ConfigMap
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: consul
        namespace: consul
      data:
        config.json: |
          {
            "ca_file": "/etc/tls/ca.pem",
            "cert_file": "/etc/tls/consul.pem",
            "key_file": "/etc/tls/consul-key.pem",
            "verify_incoming": false,
            "verify_outgoing": false,
            "verify_server_hostname": false,
            "ports": {
              "https": 8443
            }
          }

- name: Create consul StatefulSet
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: consul
        namespace: consul
      spec:
        serviceName: consul
        replicas: 3
        selector:
          matchLabels:
            app: consul
        template:
          metadata:
            labels:
              app: consul
          spec:
            securityContext:
              fsGroup: 1000
            containers:
              - name: consul
                image: "consul:1.9.0"
                env:
                  - name: POD_IP
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                  - name: GOSSIP_ENCRYPTION_KEY
                    valueFrom:
                      secretKeyRef:
                        name: consul
                        key: gossip-encryption-key
                  - name: NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                args:
                  - "agent"
                  - "-advertise=$(POD_IP)"
                  - "-bind=0.0.0.0"
                  - "-bootstrap-expect=3"
                  - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
                  - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
                  - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
                  - "-client=0.0.0.0"
                  - "-config-file=/consul/myconfig/config.json"
                  - "-datacenter=dc1"
                  - "-data-dir=/consul/data"
                  - "-domain=cluster.local"
                  - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
                  - "-server"
                  - "-ui"
                  - "-disable-host-node-id"
                volumeMounts:
                  - name: config
                    mountPath: /consul/myconfig
                  - name: tls
                    mountPath: /etc/tls
                lifecycle:
                  preStop:
                    exec:
                      command:
                      - /bin/sh
                      - -c
                      - consul leave
                ports:
                  - containerPort: 8500
                    name: ui-port
                  - containerPort: 8400
                    name: alt-port
                  - containerPort: 53
                    name: udp-port
                  - containerPort: 8443
                    name: https-port
                  - containerPort: 8080
                    name: http-port
                  - containerPort: 8301
                    name: serflan
                  - containerPort: 8302
                    name: serfwan
                  - containerPort: 8600
                    name: consuldns
                  - containerPort: 8300
                    name: server
            volumes:
              - name: config
                configMap:
                  name: consul
              - name: tls
                secret:
                  secretName: consul
