---

- name: Include metallb tasks
  include_tasks:
    file: metallb.yml
    apply:
      tags:
        - kubernetes
        - metallb
        - sunfire
  vars:
    kubernetes:
      context: sunfire
      metallb:
        dhcp:
          start: 192.168.1.170
          end: 192.168.1.199
        memberlist: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38636462356664393833313066353934393630653938356563633436333461373134313631373361
          6365376165623461333939383837373032626133383639340a313538366635356163373632643464
          64356435363161343032643561356336633437323836363332333639363637653436666638323135
          3862363630663339380a386236396164386234313963613065396361373437303633313037363362
          31666533633763363166316463613462643737313738636134313966353865316239623164303564
          62313362366335313336376465633538363433353463366537333232633832663064333563386363
          31323539623162646561343130653536306637626466613231356562333936656366643931323431
          39316532396364643164
  tags:
    - kubernetes
    - metallb
    - sunfire

- name: Include hello-world tasks
  include_tasks:
    file: hello-world.yml
    apply:
      tags:
        - kubernetes
        - hello-world
        - sunfire
  vars:
    kubernetes:
      context: sunfire
  tags:
    - kubernetes
    - hello-world
    - sunfire

- name: Include hubot tasks
  include_tasks:
    file: hubot.yml
    apply:
      tags:
        - kubernetes
        - hubot
        - sunfire
  vars:
    kubernetes:
      context: sunfire
  tags:
    - kubernetes
    - hubot
    - sunfire

- name: Include awx
  include_tasks:
    file: awx.yml
    apply:
      tags:
        - kubernetes
        - awx
        - sunfire
  vars:
    kubernetes:
      context: sunfire
  tags:
    - kubernetes
    - awx
    - sunfire

- name: Include argocd
  include_tasks:
    file: argocd.yml
    apply:
      tags:
        - kubernetes
        - argocd
        - sunfire
  vars:
    kubernetes:
      context: sunfire
  tags:
    - kubernetes
    - argocd
    - sunfire

- name: Include additional-scrape-configs
  include_tasks:
    file: additional-scrape-configs.yml
    apply:
      tags:
        - kubernetes
        - scrape
        - jonagold
  vars:
    kubernetes:
      context: jonagold
  tags:
    - kubernetes
    - scrape
    - jonagold

- name: Include grafana-image-renderer
  include_tasks:
    file: grafana-image-renderer.yml
    apply:
      tags:
        - kubernetes
        - grafana
        - jonagold
  vars:
    kubernetes:
      context: jonagold
  tags:
    - kubernetes
    - grafana
    - jonagold

- name: Include consul
  include_tasks:
    file: consul.yml
    apply:
      tags:
        - kubernetes
        - consul
        - sunfire
  vars:
    kubernetes:
      context: sunfire
  tags:
    - kubernetes
    - consul
    - sunfire

- name: Include cluster-admin
  include_tasks:
    file: cluster-admin.yml
    apply:
      tags:
        - kubernetes
        - sunfire
        - cluster-admin
  vars:
    kubernetes:
      context: sunfire
  tags:
    - kubernetes
    - sunfire
    - cluster-admin

- name: Include openldap
  include_tasks:
    file: openldap.yml
    apply:
      tags:
        - kubernetes
        - sunfire
        - openldap
  vars:
    kubernetes:
      context: sunfire
  tags:
    - kubernetes
    - sunfire
    - openldap
