---

- name: Include metallb tasks
  include_tasks: metallb.yml
  vars:
    kubernetes:
      context: sunfire
      metallb:
        dhcp:
          start: 192.168.1.170
          end: 192.168.1.199

- name: Include hello-world tasks
  include_tasks: hello-world.yml
  vars:
    kubernetes:
      context: sunfire

- name: Include hubot tasks
  include_tasks: hubot.yml
  vars:
    kubernetes:
      context: sunfire

- name: Include awx
  include_tasks: awx.yml
  vars:
    kubernetes:
      context: sunfire

- name: Include argocd
  include_tasks:
    file: argocd.yml
    apply:
      tags:
        - argocd
  vars:
    kubernetes:
      context: sunfire
  tags: argocd

- name: Include additional-scrape-configs
  include_tasks: additional-scrape-configs.yml
  vars:
    kubernetes:
      context: jonagold

- name: Include grafana-image-renderer
  include_tasks: grafana-image-renderer.yml
  vars:
    kubernetes:
      context: jonagold
