- name: Create openldap Namespace
  community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openldap

- name: Create openldap Deployment
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: openldap
        namespace: openldap
      spec:
        replicas: 1
        selector:
          matchLabels:
            name: openldap
        nodeSelector:
          kubernetes.io/arch: amd64
        template:
          nodeSelector:
            kubernetes.io/arch: amd64
          metadata:
            labels:
              name: openldap
            name: openldap
          spec:
            nodeSelector:
              kubernetes.io/arch: amd64
            containers:
            - name: openldap
              image: bitnami/openldap:2
              env:
                - name: LDAP_PORT_NUMBER
                  value: '1389'
                - name: LDAP_ADMIN_USERNAME
                  value: admin
                - name: LDAP_ADMIN_PASSWORD
                  value: password

- name: Create openladp Service
  community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes.context }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: openldap
        namespace: openldap
      spec:
        selector:
          app: openldap
        ports:
          - protocol: TCP
            port: 389
            targetPort: '1389'
            name: ldap
        type: LoadBalancer
