---

- name: Configure upstream PowerDNS repositories
  block:

    - name: Add PowerDNS apt GPG key
      apt_key:
        state: present
        id: "{{ powerdns_gpg_key_id }}"
        keyserver: keys.gnupg.net

    - name: Add PowerDNS recursor repository
      apt_repository:
        state: present
        repo: deb http://repo.powerdns.com/raspbian buster-rec-{{ powerdns_version | replace('.', '') }} main

    - name: Add PowerDNS authoritative server repository
      apt_repository:
        state: present
        repo: deb http://repo.powerdns.com/raspbian buster-auth-{{ powerdns_version | replace('.', '') }} main

    - name: Add pin-priority for PowerDNS packages
      copy:
        dest: /etc/apt/preferences.d/pdns
        owner: root
        group: root
        mode: 0644
        content: |
          Package: pdns-*
          Pin: origin repo.powerdns.com
          Pin-Priority: 600

  when:
    - ansible_architecture == 'armv7l'
    - ansible_distribution_release == 'buster'
  become: yes
