---

- name: Include variables
  include_vars:
    file: main.yml
    name: k3s

- name: Download the release
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s.version }}/k3s-{{ k3s.arch }}
    dest: /tmp/k3s-{{ k3s.arch }}
    checksum: sha256:{{ k3s.sha256 }}
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Move the release
  copy:
    src: /tmp/k3s-{{ k3s.arch }}
    remote_src: yes
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Deploy the unit
  template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Start and enable
  systemd:
    name: k3s
    state: started
    enabled: yes 
  become: yes
