---
- name: AWX Metronome
  hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tasks:
    - name: Simple ping
      action: ping

    - name: Ping Healthchecks.io
      uri:
        url: "{{ metronome.healthchecks_io }}"
