---

- name: Deploy /etc/nginx/conf.d/default.conf
  copy:
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    content: |
      server {
        listen *:80 default_server;
        add_header Front-End-Https on;
        add_header X-Content-Type-Options nosniff;
        if ($ssl_protocol = "") {
          return 308 https://$host$request_uri;
        }
        index  index.html;
        access_log /var/log/nginx/http.access.log combined;
        error_log /var/log/nginx/http.error.log;
      }
      server {
        listen *:443 ssl;
        server_name cloudmason.org;
        ssl_certificate     /etc/letsencrypt/live/cloudmason.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/cloudmason.org/privkey.pem;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 5m;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;
        root   /usr/share/nginx/html/cloudmason.org;
        index  index.php index.html index.htm;
        location / {
          try_files $uri $uri/ =404;
        }
        location /humble {
          autoindex on;
        }
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
          root /usr/share/nginx/html;
        }
        location ~ .php$ {
          try_files $uri =404;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
        }
        access_log   /var/log/nginx/https.access.log combined;
        error_log    /var/log/nginx/https.error.log;
        add_header   Front-End-Https on;
        add_header   X-Content-Type-Options nosniff;
        add_header   Access-Control-Allow-Origin *;
        add_header   Content-Security-Policy "frame-ancestors cloudmason.org";
        location /grafana/ {
          proxy_pass            http://127.0.0.1:3000/;
          proxy_read_timeout    90;
          proxy_connect_timeout 90;
          proxy_redirect        off;
          proxy_set_header Connection '';
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
          access_log   /var/log/nginx/grafana.access.log combined;
          error_log    /var/log/nginx/grafana.error.log;
        }
        location /sabnzbd/ {
          proxy_pass            http://127.0.0.1:7777/;
          proxy_read_timeout    90;
          proxy_connect_timeout 90;
          proxy_redirect        off;
          proxy_set_header      Host $host;
          proxy_set_header      X-Real-IP $remote_addr;
          proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass_header     Authorization;
          proxy_set_header Connection '';
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
          proxy_set_header Host $host;
          access_log   /var/log/nginx/sabnzbd.access.log combined;
          error_log    /var/log/nginx/sabnzbd.error.log;
          satisfy all;
          auth_basic "Authentication Required";
          auth_basic_user_file /etc/nginx/htpasswd;
        }
        location /sabnzbd/api {
          proxy_pass            http://127.0.0.1:7777/api;
          proxy_read_timeout    90;
          proxy_connect_timeout 90;
          proxy_redirect        off;
          proxy_set_header      Host $host;
          proxy_set_header      X-Real-IP $remote_addr;
          proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass_header     Authorization;
          proxy_set_header Connection '';
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
          proxy_set_header Host $host;
          access_log   /var/log/nginx/sabnzbd-api.access.log combined;
          error_log    /var/log/nginx/sabnzbd-api.error.log;
        }
        location /sonarr/ {
          proxy_pass            http://127.0.0.1:8888/sonarr/;
          proxy_read_timeout    90;
          proxy_connect_timeout 90;
          proxy_redirect        off;
          proxy_set_header      Host $host;
          proxy_set_header      X-Real-IP $remote_addr;
          proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass_header     Authorization;
          proxy_set_header Connection '';
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
          proxy_set_header Host $host;
          access_log   /var/log/nginx/sonarr.access.log combined;
          error_log    /var/log/nginx/sonarr.error.log;
          satisfy all;
          auth_basic "Authentication Required";
          auth_basic_user_file /etc/nginx/htpasswd;
        }
        location /radarr/ {
          proxy_pass            http://127.0.0.1:7878/radarr/;
          proxy_read_timeout    90;
          proxy_connect_timeout 90;
          proxy_redirect        off;
          proxy_set_header      Host $host;
          proxy_set_header      X-Real-IP $remote_addr;
          proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass_header     Authorization;
          proxy_set_header Connection '';
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
          proxy_set_header Host $host;
          access_log   /var/log/nginx/radarr.access.log combined;
          error_log    /var/log/nginx/radarr.error.log;
          satisfy all;
          auth_basic "Authentication Required";
          auth_basic_user_file /etc/nginx/htpasswd;
        }
        location /couchpotato/ {
          proxy_pass            http://127.0.0.1:5050/couchpotato/;
          proxy_read_timeout    90;
          proxy_connect_timeout 90;
          proxy_redirect        off;
          proxy_set_header      Host $host;
          proxy_set_header      X-Real-IP $remote_addr;
          proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass_header     Authorization;
          proxy_set_header Connection '';
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
          proxy_set_header Host $host;
          access_log   /var/log/nginx/couchpotato.access.log combined;
          error_log    /var/log/nginx/couchpotato.error.log;
          satisfy all;
          auth_basic "Authentication Required";
          auth_basic_user_file /etc/nginx/htpasswd;
        }
        location /stackstorm/ {
          proxy_pass            https://lenovo.cloudmason.org:4443/;
          proxy_read_timeout    90;
          proxy_connect_timeout 90;
          proxy_redirect        off;
          proxy_set_header      Host $host;
          proxy_set_header      X-Real-IP $remote_addr;
          proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass_header     Authorization;
          proxy_set_header Connection '';
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
          proxy_set_header Host $host;
          access_log   /var/log/nginx/stackstorm.access.log combined;
          error_log    /var/log/nginx/stackstorm.error.log;
        }
        location /prometheus/ {
          proxy_pass            http://localhost:9090/prometheus/;
          proxy_read_timeout    90;
          proxy_connect_timeout 90;
          proxy_redirect        off;
          access_log   /var/log/nginx/prometheus.access.log combined;
          error_log    /var/log/nginx/prometheus.error.log;
        }
        location /jenkins/ {
          proxy_pass http://localhost:8080/jenkins/;
          proxy_redirect http:// https://;
          sendfile off;
          proxy_set_header   Host             $host:$server_port;
          proxy_set_header   X-Real-IP        $remote_addr;
          proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
          proxy_max_temp_file_size 0;
          client_max_body_size       10m;
          client_body_buffer_size    128k;
          proxy_connect_timeout      90;
          proxy_send_timeout         90;
          proxy_read_timeout         90;
          proxy_temp_file_write_size 64k;
          proxy_http_version 1.1;
          proxy_request_buffering off;
          proxy_buffering off; # Required for HTTP-based CLI to work over SSL
          access_log   /var/log/nginx/jenkins.access.log combined;
          error_log    /var/log/nginx/jenkins.error.log;
          #add_header 'X-SSH-Endpoint' 'localhost:50022' always;
        }
      }
      server {
        listen *:443 ssl;
        server_name letsbuildthe.cloud;
        ssl_certificate     /etc/letsencrypt/live/letsbuildthe.cloud/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/letsbuildthe.cloud/privkey.pem;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 5m;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;
        root   /usr/share/nginx/html/letsbuildthe.cloud;
        index  index.php index.html index.htm;
        location / {
          try_files $uri $uri/ =404;
        }
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
          root /usr/share/nginx/html;
        }
        location ~ .php$ {
          try_files $uri =404;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
        }
        access_log /var/log/nginx/https.access.log combined;
        error_log  /var/log/nginx/https.error.log;
        add_header Front-End-Https on;
        add_header X-Content-Type-Options nosniff;
        add_header Access-Control-Allow-Origin *;
        add_header Content-Security-Policy "frame-ancestors letsbuildthe.cloud";
      }
  become: yes
  notify: Reload nginx

- name: Deploy /var/lib/nginx/.ssh/config (ssh config hack for multiple GH deploy keys)
  copy:
    dest: /var/lib/nginx/.ssh/config
    owner: nginx
    group: nginx
    mode: 0600
    content: |
      Host github.com-cloudmason.org
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_rsa
      Host github.com-letsbuildthe.cloud
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_rsa2
  become: yes

- name: Deploy /var/lib/nginx/.ssh/...
  copy:
    dest: /var/lib/nginx/.ssh/{{ item }}
    src: "{{ item }}"
    owner: nginx
    group: nginx
    mode: 0600
    backup: yes
  loop:
    - id_rsa
    - id_rsa2
  become: yes

- name: Deploy /var/lib/nginx/.ssh/...
  copy:
    dest: /var/lib/nginx/.ssh/{{ item }}
    src: "{{ item }}"
    owner: nginx
    group: nginx
    mode: 0644
    backup: yes
  loop:
    - id_rsa.pub
    - id_rsa2.pub
  become: yes

- name: Cloudmason ping sweep cron
  cron:
    name: Cloudmason ping sweep cron
    user: nginx
    minute: '*/20'
    job: /usr/sbin/fping -a -d -q -g 192.168.1.0/24 | sed -E 's,.cloudmason.org$,,' | paste -sd' ' >/usr/share/nginx/html/cloudmason.org/cloudmason
  become: yes

- name: fail2ban wall of shame cron
  cron:
    name: fail2-ban wall of shame cron
    minute: "*/5"
    user: root
    job: |
      /sbin/iptables -L f2b-sshd 2>/dev/null | grep REJECT | awk '{print $4}' >/usr/share/nginx/html/f2b-sshd 2>/dev/null
  become: yes
