- name: install nginx
  apt:
    name: nginx
  become: yes
  tags: cloudmason.org

- name: install python3-pip and python3-certbot-nginx
  apt:
    name:
      - python3-pip
      - python3-certbot-nginx

- name: install certbot python3-certbot-nginx
  pip:
    name:
      - certbot

- name: deploy cloudmason nginx conf
  copy:
    dest: /etc/nginx/conf.d/cloudmason.conf
    content: |
      server {
        listen *:80 default_server;
        add_header Front-End-Https on;
        add_header X-Content-Type-Options nosniff;
        if ($ssl_protocol = "") {
          return 308 https://$host$request_uri;
        }
        index  index.html;
        access_log /var/log/nginx/http.access.log combined;
        error_log /var/log/nginx/http.error.log;
      }
      server {
        listen *:443 ssl;
        ssl_certificate     /etc/letsencrypt/live/cloudmason.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/cloudmason.org/privkey.pem;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 5m;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-GCM-SHA384:ECDHE
        ssl_prefer_server_ciphers on;
        root   /usr/share/nginx/html;
        index  index.php index.html index.htm;
        location / {
          try_files $uri $uri/ =404;
        }
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
          root /usr/share/nginx/html;
        }
        access_log   /var/log/nginx/https.access.log combined;
        error_log    /var/log/nginx/https.error.log;
        add_header   Front-End-Https on;
        add_header   X-Content-Type-Options nosniff;
        add_header   Access-Control-Allow-Origin *;
        add_header   Content-Security-Policy "frame-ancestors cloudmason.org";
      }
