---

- name: AWX / infra
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Include awx role (infra)
      include_role:
        name: awx
        tasks_from: infra.yml
      vars:
        context: thinkpad
  tags:
    - infra

- name: AWX / Get admin password
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Get admin password
      ansible.builtin.shell:
        cmd: |
          kubectl -n awx get secret awx-admin-password -o json | jq -r .data.password | base64 -d
      register: admin_password
      no_log: true
      changed_when: false  # Don't care
    - name: Register admin password
      ansible.builtin.set_fact:
        admin_password: "{{ admin_password.stdout | trim }}"
      no_log: true
  tags:
    - always

- name: AWX / deploy_user
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Include awx role (config)
      include_role:
        name: awx
        tasks_from: config.yml
      vars:
        TOWER_HOST: https://awx-dev.cloudmason.org
        TOWER_USERNAME: admin
        TOWER_PASSWORD: "{{ admin_password }}"
  tags:
    - config

# - name: AWX / config
#   hosts: localhost
#   connection: local
#   gather_facts: false
#   become: false
#   tasks:
#     - name: Include awx role (config)
#       include_role:
#         name: awx
#         tasks_from: config.yml
#   tags:
#     - awx
#     - config

# - name: AWX / metronome
#   hosts: localhost
#   connection: local
#   gather_facts: false
#   become: false
#   tasks:
#     - name: Include awx role (metronome)
#       include_role:
#         name: awx
#         tasks_from: metronome.yml
#   tags:
#     - awx
#     - metronome

# - name: AWX / user
#   hosts: "{{ ansible_limit | default(omit) }}"
#   gather_facts: false
#   become: false
#   tasks:
#     - name: Include awx role (user)
#       include_role:
#         name: awx
#         tasks_from: user.yml
#   tags:
#     - awx
#     - user
