---
- name: AWX
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: no
  become: no

  tasks:

    - name: Create awx group
      group:
        state: present
        name: awx
      become: yes

    - name: Create awx user
      user:
        state: present
        name: awx
        groups: awx
        comment: AWX Service Account
        shell: /bin/bash
        create_home: yes
      become: yes

    - name: Create ~awx/.ssh
      file:
        state: directory
        path: /home/awx/.ssh
        owner: awx
        group: awx
        mode: 0700
      become: yes

    - name: Deploy ~awx/.ssh/authorized_keys
      copy:
        dest: /home/awx/.ssh/authorized_keys
        owner: awx
        group: awx
        mode: 0600
        content: "{{ awx.awx.ssh_pub_key }}"
      become: yes

    - name: Deploy ~awx/.ssh/id_rsa.pub
      copy:
        dest: /home/awx/.ssh/id_rsa.pub
        owner: awx
        group: awx
        mode: 0600
        content: "{{ awx.awx.ssh_pub_key }}"
      become: yes

    - name: Deploy ~awx/.ssh/id_rsa
      copy:
        dest: /home/awx/.ssh/id_rsa
        owner: awx
        group: awx
        mode: 0600
        content: "{{ awx.awx.ssh_key_data }}"
      become: yes

    - name: Give awx passwordless sudo
      copy:
        dest: /etc/sudoers.d/awx
        owner: root
        group: root
        mode: 0440
        content: |
          awx ALL=(ALL) NOPASSWD: ALL
      become: yes
