---
- name: Check DNS
  hosts: all
  gather_facts: no

  vars:
    records:
      - facebook.com.
      - google.com.
      - reddit.com.
      - twitter.com.
      - mamercad.myqnapcloud.com
      - letsbuildthe.cloud.
      - cloudmason.org.
      - gateway.cloudmason.org.
      - cloudkey.cloudmason.org.
      - net1.cloudmason.org.
      - net2.cloudmason.org.
      - powerdns1.cloudmason.org.
      - powerdns2.cloudmason.org.
      - -t ptr 1.1.168.192.in-addr.arpa.

  tasks:

    - name: Check
      command: |
        dig @{{ item.0 }} +short {{ item.1 }}
      register: foo
      with_nested:
        - "{{ network.dns.nameservers }}"
        - "{{ records }}"
      changed_when: no # Don't care

    - name: Debug
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ foo.results }}"
      failed_when: item.stdout == ''
