---
- name: hello
  hosts: "{{ ansible_limit | default(omit) }}"
  connection: "{{ 'local' if ansible_limit == 'localhost' else 'ssh' }}"
  gather_facts: false
  become: false
  tasks:
    - name: hello
      ansible.builtin.debug:
        msg: hello
