---
- name: K3s
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: true
  become: false

  tasks:

    - name: Include K3s role (armv7l)
      include_role:
        name: k3s
      vars:
        k3s:
          version: v1.20.4%2Bk3s1
          binary: k3s-armhf
          sha256: 6567e3773022bd1a44514ddfb4da74efd2ec6cbb6b30ea5f89e70c4590173763
      when: ansible_architecture == "armv7l"

    - name: Include K3s role (amd64)
      include_role:
        name: k3s
      vars:
        k3s:
          version: v1.20.4%2Bk3s1
          binary: k3s
          sha256: 1c7b68b0b7d54f21a9c1727545a7db181668115f161a3986bc137261dd817e98
      when: ansible_architecture == "x86_64"
