---
- name: k3s
  hosts:
    - nodes
    - clusterpis
  gather_facts: yes
  become: no

  pre_tasks:

    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
        k3s_control_node_address: node0
        k3s_primary_control_node: true
        k3s_etcd_datastore: true
        k3s_release_version: v1.20.0+k3s2
        k3s_become_for_all: yes
      when: inventory_hostname in ['node0']

    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
        k3s_control_node_address: node0
        k3s_primary_control_node: false
        k3s_etcd_datastore: true
        k3s_release_version: v1.20.0+k3s2
        k3s_become_for_all: yes
      when: inventory_hostname in ['node1', 'node2']

    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: false
        k3s_control_node_address: node0
        k3s_release_version: v1.20.0+k3s2
        k3s_become_for_all: yes
      when: inventory_hostname in ['node3', 'node4', 'node5']

    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: false
        k3s_control_node_address: node0
        k3s_release_version: v1.20.0+k3s2
        k3s_become_for_all: yes
      when: inventory_hostname in ['clusterpi0', 'clusterpi1', 'clusterpi2', 'clusterpi3', 'clusterpi4']

  roles:
    - { role: xanmanning.k3s }
