---
- name: octodns
  hosts: all
  gather_facts: no
  vars:
    ansible_python_interpreter: /opt/octodns/bin/python
  tasks:
    - name: pwd
      command: pwd
      register: pwd
    - debug:
        var: pwd
    # - name: octodns-sync
    #   command: /opt/octodns/bin/octodns-sync --config config/production.yaml
