---
- name: octodns
  hosts: jonagold
  gather_facts: no

  vars:
    ansible_python_interpreter: /opt/octodns/bin/python
    eth0: 68.46.132.66
    eth2: 162.230.47.152

  tasks:

    - name: clone git@github.com:mamercad/cloudmason.git
      git:
        repo: git@github.com:mamercad/cloudmason.git
        dest: /home/awx/src/github.com/mamercad/cloudmason
        key_file: /home/awx/.ssh/id_rsa
        accept_hostkey: yes
      become: yes
      become_user: awx

    - name: do the mo templates
      shell: |
        ../scripts/mo config/external/letsbuildthe.cloud.yaml.mo | tee config/external/letsbuildthe.cloud.yaml
        ../scripts/mo config/external/cloudmason.org.yaml.mo | tee config/external/cloudmason.org.yaml
      args:
        chdir: /home/awx/src/github.com/mamercad/cloudmason/octodns
      environment:
        eth2: "{{ eth2 }}"
        eth0: "{{ eth0 }}"
      become: yes
      become_user: awx

    - name: octodns-sync
      shell: |
        /opt/octodns/bin/octodns-sync --config config/external.yaml --doit;
        /opt/octodns/bin/octodns-sync --config config/internal.yaml --doit;
      args:
        chdir: /home/awx/src/github.com/mamercad/cloudmason/octodns
      environment:
        POWERDNS_API_KEY: "{{ lookup('env', 'POWERDNS_API_KEY') }}"
        CLOUDFLARE_API_KEY: "{{ lookup('env', 'CLOUDFLARE_API_KEY') }}"
      register: octodns_sync
      changed_when: no # Don't care, we'll see the results below
      become: yes
      become_user: awx

    - name: show the results of the sync
      pause:
        seconds: 1
        prompt: |
          {% for line in octodns_sync.stderr_lines %}
          {{ line }}
          {% endfor %}
      become: yes
      become_user: awx
