---
- name: PowerDNS
  hosts: powerdns_servers
  gather_facts: true
  become: false
  tasks:
    - name: Include powerdns role (main)
      include_role:
        name: powerdns
        tasks_from: main.yml
