---
- name: PowerDNS
  hosts: powerdns_servers
  gather_facts: true
  become: false

  vars:

    database_name: /var/lib/powerdns/db.sqlite

    pdns_config:
      master: true
      slave: false
      local-address: "0.0.0.0:5353"
      api: true
      api-key: "{{ powerdns.api_key }}"
      webserver: true
      webserver-address: "0.0.0.0"
      webserver-port: "8081"
      webserver-allow-from: "{{ network.cidr }}"

    pdns_backends:
      gsqlite3:
        database: "{{ database_name }}"
        dnssec: false

    pdns_install_repo: "{{ pdns_auth_powerdns_repo_44 }}"

    pdns_sqlite_databases_locations:
      - "{{ database_name }}"

    pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_44 }}"

    pdns_rec_config:
      allow-from: "127.0.0.0/8,{{ network.cidr_wide }}"
      forward-zones: "{{ powerdns.forward_zones }}"
      local-address: "0.0.0.0:53"
      webserver: true
      webserver-address: "0.0.0.0"
      webserver-port: "8082"
      webserver-allow-from: "{{ network.cidr }}"

    dns_checks:
      - localhost/A
      - example.com./A
      - google.com/A
      - reddit.com/A
      - twitter.com/A
      - digitalocean.com/A
      - cloudmason.org/A
      - cloudmason.org/MX
      - letsbuildthe.cloud/A
      - letsbuildthe.cloud/MX
      - gateway.cloudmason.org/A
      - 192.168.1.1/PTR
      - 192.168.1.10/PTR
      - 192.168.1.11/PTR
      - 192.168.1.67/PTR

  pre_tasks:

    - name: Remove avahi-daemon
      ansible.builtin.apt:
        name: avahi-daemon
        state: absent
      become: true

    - name: Stop/disable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: false
      become: true

    - name: Deploy /etc/resolv.conf
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        backup: true
        owner: root
        group: root
        mode: 0644
        content: |
          nameserver 192.168.1.10
          domain {{ network.domain }}
          search {{ network.domain }}
      become: true

  roles:

    - role: PowerDNS.pdns
      become: true

    - role: PowerDNS.pdns_recursor
      become: true

  tasks:

    - name: Check DNS
      block:

        - name: Check DNS
          ansible.builtin.debug:
            msg: "{{ lookup('community.general.dig', item) }}"
          loop: "{{ dns_checks }}"
