---
- name: PowerDNS
  hosts: powerdns_servers
  gather_facts: true
  become: false

  vars:

    database_name: /var/lib/powerdns/db.sqlite

    pdns_config:
      master: true
      slave: false
      local-address: "{{ ansible_host }}"
      api: true
      api-key: "powerdns"
      webserver: true
      webserver-address: "0.0.0.0"
      webserver-port: "8001"

    pdns_backends:
      gsqlite3:
        database: "{{ database_name }}"
        dnssec: false

    pdns_install_repo: "{{ pdns_auth_powerdns_repo_44 }}"

    pdns_sqlite_databases_locations:
      - "{{ database_name }}"

    pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_44 }}"

    pdns_rec_config:
      allow-from: "{{ network.cidr_wide }}"
      local-address: "{{ ansible_host }}:5300"
      webserver: true
      webserver-address: "0.0.0.0"
      webserver-port: "8081"

  roles:

    - role: PowerDNS.pdns
      become: true

    - role: PowerDNS.pdns_recursor
      become: true
