---
- name: Slack
  hosts: net
  gather_facts: no
  serial: 1

  vars:

    ago: 10800
    width: 1000
    height: 350
    imgdir: /usr/share/nginx/html/cloudmason.org/grafana
    imgurl: https://cloudmason.org/grafana
    org: 4KC9HzbGz
    grafana: https://grafana.cloudmason.org/render/d-solo/{{ org }}/{{ item }}?orgId=1&from={{f.stdout}}000&to={{t.stdout}}000&panelId=2&width={{ width }}&height={{ height }}&tz=America%2FDetroit
    graphs:
      - load-average

  tasks:

    - name: Ensure imgdir exists
      file:
        state: directory
        path: "{{ imgdir }}"
        owner: root
        group: root
        mode: 0755
      become: yes

    - shell: expr $(date +%s) - {{ ago }}
      register: f

    - shell: expr $(date +%s)
      register: t

    - get_url:
        url: "{{ grafana }}"
        dest: "{{ imgdir }}/{{ item }}.png"
        timeout: 120
      become: yes
      loop: "{{ graphs }}"

    - set_fact:
        slack_merged: "{{ slack | combine(slack_override|default({})) }}"

    - name: Send notification message via Slack
      community.general.slack:
        token: "{{ slack_merged.ansible.token }}"
        channel: "{{ slack_merged.channel }}"
        username: "{{ slack_merged.username }}"
        icon_url: "{{ slack_merged.icon_url }}"
        blocks:
          - type: image
            image_url: "{{ imgurl }}/{{ item }}.png"
            alt_text: "{{ item }}"
      loop: "{{ graphs }}"
      when: inventory_hostname == ansible_play_hosts_all[-1]
