---
- name: Slack
  hosts: all
  gather_facts: no

  tasks:

    - uri:
        url: http://prometheus.cloudmason.org:9090/api/v1/query
        method: POST
        body: 'query=sum(increase(sense_daily_usage[1d]))'
        body_format: form-urlencoded
        return_content: yes
      register: energy

    - set_fact:
        daily_energy_use: "{{ energy.json.data.result.0.value.1 | float | round(1, 'ceil') }}"

    - name: Send notification message via Slack
      community.general.slack:
        token: "{{ slack.token }}"
        channel: "#general"
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "```Today's energy use was {{ daily_energy_use }} kWh```"
