---
- name: Slack
  hosts: all
  gather_facts: no

  tasks:

    - name: Install prereqs
      apt:
        name:
          - fortune
          - fortunes
          - fortunes-bofh-excuses

    - shell: fortune bofh-excuses linuxcookie computers linux
      register: fortune

    - name: Send notification message via Slack
      community.general.slack:
        token: "{{ slack.token }}"
        channel: "#general"
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "```{{ fortune.stdout_lines | join('\n') }}```"
