---
- name: Slack
  hosts: all
  gather_facts: yes

  tasks:

    - uri:
        url: http://prometheus.cloudmason.org:9090/api/v1/query
        method: POST
        body: 'query=node_reboot_required>0'
        body_format: form-urlencoded
        return_content: yes
      register: reboot

    - set_fact:
        needing_reboots: "{{ needing_reboots|default([]) + [ item.metric.instance | replace('.cloudmason.org:9100', '') ] }}"
      loop: "{{ reboot.json.data.result }}"
      when: reboot is defined

    - set_fact:
        needing_reboots_list: "{{ needing_reboots | map('regex_replace', '^', '  ') }}"
      when:
        - reboot is defined
        - needing_reboots is defined

    - set_fact:
        slack_reboots: "Systems needing reboot\n{{ needing_reboots_list | sort | join('\n') }}"
      when:
        - reboot is defined
        - needing_reboots is defined
        - needing_reboots_list is defined

    - uri:
        url: http://prometheus.cloudmason.org:9090/api/v1/query
        method: POST
        body: 'query=apt_upgrades_pending>0'
        body_format: form-urlencoded
        return_content: yes
      register: upgrades

    - set_fact:
        needing_upgrades: "{{ needing_upgrades|default([]) + [ (item.metric.instance + ' / ' + item.metric.origin|default('') + ' (' + item.value.1 + ')') | replace('.cloudmason.org:9100', '') ] }}"
      loop: "{{ upgrades.json.data.result }}"
      when: upgrades is defined

    - set_fact:
        needing_upgrades_list: "{{ needing_upgrades | map('regex_replace', '^', '  ') }}"
      when:
        - upgrades is defined
        - needing_upgrades is defined

    - set_fact:
        slack_upgrades: "Systems needing upgrades\n{{ needing_upgrades_list | sort | join('\n') }}"
      when:
        - upgrades is defined
        - needing_upgrades is defined
        - needing_upgrades_list is defined

    - set_fact:
        slack_reboots: No systems need rebooting
      when: slack_reboots is not defined

    - set_fact:
        slack_upgrades: No systems need upgrading
      when: slack_upgrades is not defined

    - name: Send notification message via Slack
      community.general.slack:
        token: "{{ slack.ansible.token }}"
        channel: "#general"
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "```{{ slack_reboots }}```"
      when: slack_reboots is defined

    - name: Send notification message via Slack
      community.general.slack:
        token: "{{ slack.ansible.token }}"
        channel: "#general"
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "```{{ slack_upgrades }}```"
      when: slack_upgrades is defined
