---
- name: Slack
  hosts: all
  gather_facts: no

  tasks:

    - name: Install prereqs
      apt:
        name:
          - fortune
          - fortunes
          - fortunes-bofh-excuses

    - shell: fortune bofh-excuses linuxcookie computers linux
      register: fortune

    - include_role:
        name: slack
      vars:
        slack_channel: "#testing"
        slack_message: "```{{ fortune.stdout_lines | join('\n') }}```"
