---
- name: Slack
  hosts: all
  gather_facts: no

  tasks:

    - uri:
        url: http://prometheus.cloudmason.org:9090/api/v1/query
        method: POST
        body: 'query=sum(increase(unifipoller_device_wan_receive_bytes_total{port="wan"}[1d]))'
        body_format: form-urlencoded
        return_content: yes
      register: xfinity

    - set_fact:
        daily_xfinity_traffic: "{{ xfinity.json.data.result.0.value.1 | filesizeformat(True) }}"

    - uri:
        url: http://prometheus.cloudmason.org:9090/api/v1/query
        method: POST
        body: 'query=sum(increase(unifipoller_device_wan_receive_bytes_total{port="lan2"}[1d]))'
        body_format: form-urlencoded
        return_content: yes
      register: att

    - set_fact:
        daily_att_traffic: "{{ att.json.data.result.0.value.1 | filesizeformat(True) }}"

    - set_fact:
        slack_merged: "{{ slack | combine(slack_override|default({})) }}"

    - name: Send notification message via Slack
      community.general.slack:
        token: "{{ slack_merged.ansible.token }}"
        channel: "{{ slack_merged.channel }}"
        username: "{{ slack_merged.username }}"
        icon_url: "{{ slack_merged.icon_url }}"
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "```Today's Xfinity traffic was {{ daily_xfinity_traffic }}, AT&T traffic was {{ daily_att_traffic }}```"
