---
- name: Ubuntu / main
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: true
  become: false

  tasks:

    - name: Include ubuntu role (main)
      include_role:
        name: ubuntu
        tasks_from: main.yml

    - name: Include ubuntu role (thelounge)
      include_role:
        name: ubuntu
        tasks_from: thelounge.yml
      when: thelounge | default(False, True)

    - name: Include ubuntu role (hypervisor)
      include_role:
        name: ubuntu
        tasks_from: hypervisor.yml
      when: hypervisor | default(False, True)
