---
- name: Ubuntu / mark
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: yes
  become: no

  tasks:

    - name: Include ubuntu role (mark)
      include_role:
        name: ubuntu
        tasks_from: mark.yml
