---
- name: Zabbix / server
  hosts: zabbix_servers
  gather_facts: true
  become: false
  tasks:
    - name: Include zabbix role (server)
      include_role:
        name: zabbix
        tasks_from: server.yml
        apply:
          tags: ['server']
      tags: ['server']
    # - name: Include zabbix role (config)
    #   include_role:
    #     name: zabbix
    #     tasks_from: config.yml
    #     apply:
    #       tags: ['server']
    #   tags: ['server']

- name: Zabbix / agent
  hosts: zabbix_clients
  gather_facts: true
  become: false
  tasks:
    - name: Include zabbix role (agent)
      include_role:
        name: zabbix
        tasks_from: agent.yml
        apply:
          tags: ['agent']
      tags: ['agent']
