---
- name: Zabbix / server
  hosts: thinkpad
  gather_facts: true
  become: false
  tasks:
    - name: Include zabbix role (server)
      include_role:
        name: zabbix
        tasks_from: server.yml
      vars:
        zabbix_source_ip: 192.168.1.139
        zabbix_server: 192.168.1.139
    - name: Include zabbix role (config)
      include_role:
        name: zabbix
        tasks_from: config.yml
      vars:
        mark_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30633830396334623565343036613730623738353439613533326633303431643361623732363036
          6535396562376164386136653839643766616137626531650a376264336137353331353066616631
          38636666396161383732323432336631663136656133383265353234376630613963396131326336
          3534646630643061320a656333616631653035333430376233323437623066313664353161353064
          3132
        zabbix_source_ip: 192.168.1.139
        zabbix_server: 192.168.1.139
        server_url: http://thinkpad/zabbix/
        login_user: Admin
        login_password: zabbix
        linux_servers:
          - dns: thinkpad
            ip: 192.168.1.139
          - dns: gala
            ip: 192.168.1.138
          - dns: lenovo
            ip: 192.168.1.89
          - dns: net1
            ip: 192.168.1.10
          - dns: net2
            ip: 192.168.1.11
        unifi_devices:
          - dns: gateway
            ip: 192.168.1.1
          - dns: switch1
            ip: 192.168.1.95
          - dns: switch2
            ip: 192.168.1.40
          - dns: switch3
            ip: 192.168.1.70
          - dns: switch4
            ip: 192.168.1.137
          - dns: basement
            ip: 192.168.1.63
          - dns: bedroom
            ip: 192.168.1.124
          - dns: familyroom
            ip: 192.168.1.120
        printers:
          - dns: printer
            ip: 192.168.1.134
        ping_servers:
          - dns: dns.google
            ip: 8.8.8.8
          - dns: one.one.one.one
            ip: 1.1.1.1

- name: Zabbix / agent
  hosts: thinkpad:lenovo:net1:net2
  gather_facts: true
  become: false
  tasks:
    - name: Include zabbix role (agent)
      include_role:
        name: zabbix
        tasks_from: agent.yml
      vars:
        zabbix_server: 192.168.1.139
