---
- name: Zabbix / server
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: true
  become: false

  tasks:

    - name: Include zabbix role (server)
      include_role:
        name: zabbix
        tasks_from: server.yml
