---
- name: Zabbix / main
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: true
  become: false

  tasks:

    - name: Include zabbix role (main)
      include_role:
        name: zabbix
        tasks_from: main.yml
