- name: restart-zabbix-server
  ansible.builtin.systemd:
    name: zabbix-server
    state: restarted
  become: true

- name: reload-apache2
  ansible.builtin.systemd:
    name: apache2
    state: reloaded
  become: true

- name: restart-apache2
  ansible.builtin.systemd:
    name: apache2
    state: restarted
  become: true

- name: restart-zabbix-server
  ansible.builtin.systemd:
    name: zabbix-server
    state: restarted
  become: true

- name: restart-zabbix-agent
  ansible.builtin.systemd:
    name: zabbix-agent
    state: restarted
  become: true
