---
gateway:
  type: A
  value: 192.168.1.1
cloudkey:
  type: A
  value: 192.168.1.2
dns1:
  type: A
  value: 192.168.1.10
dns2:
  type: A
  value: 192.168.1.11
printer:
  type: A
  value: 192.168.1.14
ringdoorbell:
  type: A
  value: 192.168.1.16
openhab:
  type: A
  value: 192.168.1.20
