---
manager:
  max_workers: 4

providers:
  internal:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config/internal
    default_ttl: 3600
    enforce_order: False # I'd rather order by IP
  net1:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.10
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - net1.cloudmason.org.
      - net2.cloudmason.org.
      - net5.cloudmason.org.
      - net6.cloudmason.org.
    nameserver_ttl: 3600
  net2:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.11
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - net1.cloudmason.org.
      - net2.cloudmason.org.
      - net5.cloudmason.org.
      - net6.cloudmason.org.
    nameserver_ttl: 3600
  net3:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.12
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - net1.cloudmason.org.
      - net2.cloudmason.org.
      - net5.cloudmason.org.
      - net6.cloudmason.org.
    nameserver_ttl: 3600
  net4:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.13
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - net1.cloudmason.org.
      - net2.cloudmason.org.
      - net5.cloudmason.org.
      - net6.cloudmason.org.
    nameserver_ttl: 3600
  net5:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.8
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - net1.cloudmason.org.
      - net2.cloudmason.org.
      - net5.cloudmason.org.
      - net6.cloudmason.org.
    nameserver_ttl: 3600
  net6:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.9
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - net1.cloudmason.org.
      - net2.cloudmason.org.
      - net5.cloudmason.org.
      - net6.cloudmason.org.
    nameserver_ttl: 3600

zones:
  cloudmason.org.:
    sources:
      - internal
    targets:
      - net1
      - net2
      - net5
      - net6
  1.168.192.in-addr.arpa.:
    sources:
      - internal
    targets:
      - net1
      - net2
      - net5
      - net6
  letsbuildthe.cloud.:
    sources:
      - internal
    targets:
      - net1
      - net2
      - net5
      - net6
