---
manager:
  max_workers: 4

providers:
  internal:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config/internal
    default_ttl: 3600
    enforce_order: False # I'd rather order by IP
  powerdns1:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.8
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - powerdns1.cloudmason.org.
      - powerdns2.cloudmason.org.
    nameserver_ttl: 3600
  powerdns2:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.9
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - powerdns1.cloudmason.org.
      - powerdns2.cloudmason.org.
    nameserver_ttl: 3600
  net1:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.10
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - net1.cloudmason.org.
      # - net2.cloudmason.org.
      # - net3.cloudmason.org.
      # - net4.cloudmason.org.
    nameserver_ttl: 3600
  net2:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.11
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - net1.cloudmason.org.
      # - net2.cloudmason.org.
      # - net3.cloudmason.org.
      # - net4.cloudmason.org.
    nameserver_ttl: 3600
  net3:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.12
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - net1.cloudmason.org.
      # - net2.cloudmason.org.
      # - net3.cloudmason.org.
      # - net4.cloudmason.org.
    nameserver_ttl: 3600
  net4:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.12
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - net1.cloudmason.org.
      # - net2.cloudmason.org.
      # - net3.cloudmason.org.
      # - net4.cloudmason.org.
    nameserver_ttl: 3600

zones:
  cloudmason.org.:
    sources:
      - internal
    targets:
      - net1
      # - net2
  1.168.192.in-addr.arpa.:
    sources:
      - internal
    targets:
      - net1
      # - net2
      # - net3
      # - net4
  letsbuildthe.cloud.:
    sources:
      - internal
    targets:
      - net1
      # - net2
      # - net3
      # - net4
