---
manager:
  max_workers: 2

providers:
  internal:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config/internal
    default_ttl: 3600
    enforce_order: False # I'd rather order by IP
  external:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config/external
    default_ttl: 3600
    enforce_order: False # I'd rather order by IP
  powerdns1:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.8
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - powerdns1.cloudmason.org.
      - powerdns2.cloudmason.org.
    nameserver_ttl: 3600
  powerdns2:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.9
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - powerdns1.cloudmason.org.
      - powerdns2.cloudmason.org.
    nameserver_ttl: 3600
  dns2:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.11
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - dns2.cloudmason.org.
    nameserver_ttl: 3600
  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_API_KEY

zones:
  cloudmason.org.:
    sources:
      - internal
    targets:
      # - dns2
      - powerdns1
      - powerdns2
  1.168.192.in-addr.arpa.:
    sources:
      - internal
    targets:
      # - dns2
      - powerdns1
      - powerdns2
  letsbuildthe.cloud.:
    sources:
      - external
    targets:
      - cloudflare
  cloudmason.org.:
    sources:
      - external
    targets:
      - cloudflare
