---
manager:
  max_workers: 2

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 3600
    enforce_order: False # I'd rather order by IP
  dns1:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.131
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - dns1.cloudmason.org.
      - dns2.cloudmason.org.
    nameserver_ttl: 3600
  dns2:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 192.168.1.137
    api_key: env/POWERDNS_API_KEY
    port: 8081
    nameserver_values:
      - dns1.cloudmason.org.
      - dns2.cloudmason.org.
    nameserver_ttl: 3600

zones:
  cloudmason.org.:
    sources:
      - config
    targets:
      - dns1
      - dns2
