- name: restart-network-manager
  ansible.builtin.systemd:
    name: network-manager
    state: restarted
  become: true

- name: netplan-try
  ansible.builtin.shell:
    cmd: netplan try
  become: true
