- name: Download the prometheus tarball
  ansible.builtin.get_url:
    url: "{{ release_tarball }}"
    dest: /tmp/prometheus.tgz
    checksum: "sha256:{{ release_sha256 }}"
  become: true

- name: Create prometheus group
  ansible.builtin.group:
    state: present
    name: prometheus
  become: true

- name: Create prometheus user
  ansible.builtin.user:
    state: present
    name: prometheus
    group: prometheus
    home: /opt/prometheus
    shell: /bin/bash
  become: true

- name: Create /opt/prometheus
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    owner: prometheus
    group: prometheus
  become: true

- name: Unarchive prometheus tarball
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tgz
    dest: /opt/prometheus
    remote_src: yes
  become: true

- name: Create /opt/prometheus/storage
  ansible.builtin.file:
    state: directory
    path: /opt/prometheus/storage
    owner: prometheus
    group: prometheus
    mode: 0755
  become: true

- name: Build prometheus targets (node_exporter)
  ansible.builtin.set_fact:
    node_exporter_targets: "{{ node_exporter_targets|default([],True) + [item + '.' + network.domain + ':9100'] }}"
  loop: "{{ groups.prometheus_clients }}"
  run_once: true

- name: Build grafana targets (grafana)
  ansible.builtin.set_fact:
    grafana_targets: "{{ grafana_targets|default([],True) + [item + '.' + network.domain + ':443'] }}"
  loop: "{{ groups.grafana_servers }}"
  run_once: true

- name: Build prometheus targets (unifi_pollers)
  ansible.builtin.set_fact:
    unifi_pollers: "{{ unifi_pollers|default([],True) + [item + '.' + network.domain + ':9130'] }}"
  loop: "{{ groups.unifi_pollers }}"
  run_once: true

- name: Deploy prometheus config
  ansible.builtin.copy:
    dest: /opt/prometheus/prometheus-{{ version }}.linux-amd64/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644
    content: |
      global:
        scrape_interval: 1m
        scrape_timeout: 30s
        evaluation_interval: 15m
      alerting:
        alertmanagers:
        - static_configs:
          - targets: []
      rule_files: []
      scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets: {{ node_exporter_targets }}
        - job_name: grafana
          scheme: https
          static_configs:
          - targets: {{ grafana_targets }}
        # - job_name: unifi
        #   static_configs:
        #   - targets: {{ unifi_pollers }}
        #   scrape_interval: 15m
        #   scrape_timeout: 5m
        - job_name: 'snmp'
          static_configs:
            - targets:
              - 192.168.1.1  # gateway
              - 192.168.1.63  # basement
              - 192.168.1.87  # diningroom
              - 192.168.1.120  # familyroom
              - 192.168.1.124  # bedroom
          metrics_path: /snmp
          params:
            module: [if_mib]
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: 127.0.0.1:9116  # The SNMP exporter's real hostname:port.
          scrape_interval: 15m
          scrape_timeout: 5m
  notify: restart-prometheus
  become: true

- name: Deploy prometheus systemd unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/opt/prometheus/prometheus-{{ version }}.linux-amd64/prometheus \
          --config.file /opt/prometheus/prometheus-{{ version }}.linux-amd64/prometheus.yml \
          --storage.tsdb.path /opt/prometheus/storage
      [Install]
      WantedBy=multi-user.target
  become: true

- name: Start and enable prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
  become: true
