- name: Download the prometheus tarball
  ansible.builtin.get_url:
    url: "{{ release_tarball }}"
    dest: /tmp/prometheus.tgz
    checksum: "sha256:{{ release_sha256 }}"
  become: true

- name: Create prometheus group
  ansible.builtin.group:
    state: present
    name: prometheus
  become: true

- name: Create prometheus user
  ansible.builtin.user:
    state: present
    name: prometheus
    group: prometheus
    home: /opt/prometheus
    shell: /bin/bash
  become: true

- name: Create /opt/prometheus
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    owner: prometheus
    group: prometheus
  become: true

- name: Unarchive prometheus tarball
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tgz
    dest: /opt/prometheus
    remote_src: yes
  become: true

- name: Create /opt/prometheus/storage
  ansible.builtin.file:
    state: directory
    path: /opt/prometheus/storage
    owner: prometheus
    group: prometheus
    mode: 0755
  become: true

- name: Deploy prometheus config
  ansible.builtin.copy:
    dest: /opt/prometheus/prometheus-{{ version }}.linux-amd64/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644
    content: |
      # my global config
      global:
        scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
        evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
        # scrape_timeout is set to the global default (10s).
      # Alertmanager configuration
      alerting:
        alertmanagers:
        - static_configs:
          - targets:
            # - alertmanager:9093
      # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
      rule_files:
        # - "first_rules.yml"
        # - "second_rules.yml"
      # A scrape configuration containing exactly one endpoint to scrape:
      # Here it's Prometheus itself.
      scrape_configs:
        # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
        - job_name: 'prometheus'
          # metrics_path defaults to '/metrics'
          # scheme defaults to 'http'.
          static_configs:
          - targets: ['localhost:9090']
  become: true

- name: Deploy prometheus systemd unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/opt/prometheus/prometheus-{{ version }}.linux-amd64/prometheus \
          --config.file /opt/prometheus/prometheus-{{ version }}.linux-amd64/prometheus.yml \
          --storage.tsdb.path /opt/prometheus/storage
      [Install]
      WantedBy=multi-user.target
  become: true

- name: Start and enable prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
  become: true
