- name: Download the prometheus tarball
  ansible.builtin.get_url:
    url: "{{ release_tarball }}"
    dest: /tmp/prometheus.tgz
    checksum: "sha256:{{ release_sha256 }}"
  become: true

- name: Create prometheus group
  ansible.builtin.group:
    state: present
    name: prometheus
  become: true

- name: Create prometheus user
  ansible.builtin.user:
    state: present
    name: prometheus
    group: prometheus
    home: /opt/prometheus
    shell: /bin/bash
  become: true

- name: Create /opt/prometheus
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    owner: prometheus
    group: prometheus
  become: true

- name: Unarchive prometheus tarball
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tgz
    dest: /opt/prometheus
    remote_src: yes
  become: true

- name: Create /opt/prometheus/storage
  ansible.builtin.file:
    state: directory
    path: /opt/prometheus/storage
    owner: prometheus
    group: prometheus
    mode: 0755
  become: true

- name: Build prometheus targets
  ansible.builtin.set_fact:
    targets: "{{ targets|default([],True) + [item + '.' + network.domain + ':9100'] }}"
  loop: "{{ groups.prometheus_clients }}"
  run_once: true

- name: Deploy prometheus config
  ansible.builtin.copy:
    dest: /opt/prometheus/prometheus-{{ version }}.linux-amd64/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644
    content: |
      global:
        scrape_interval: 1m
        evaluation_interval: 1m
      alerting:
        alertmanagers:
        - static_configs:
          - targets: []
      rule_files: []
      scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets: {{ targets }}
  notify: restart-prometheus
  become: true

- name: Deploy prometheus systemd unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/opt/prometheus/prometheus-{{ version }}.linux-amd64/prometheus \
          --config.file /opt/prometheus/prometheus-{{ version }}.linux-amd64/prometheus.yml \
          --storage.tsdb.path /opt/prometheus/storage
      [Install]
      WantedBy=multi-user.target
  become: true

- name: Start and enable prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
  become: true
