---

- name: Install nginx and php-fpm
  apt:
    state: present
    name:
      - nginx
      - php-fpm
  become: yes

- name: Check if /etc/nginx/sites-enabled/default exists
  stat:
    path: /etc/nginx/sites-enabled/default
  register: default
  become: yes

- name: Move /etc/nginx/sites-enabled/default out of the way
  shell: rm -f /etc/nginx/sites-enabled/default
  when: default.stat.islnk is defined
  notify: Reload nginx
  become: yes

- name: Deploy /etc/nginx/conf.d/default.conf
  copy:
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    content: |
      server {
        listen *:80 default_server;
        add_header Front-End-Https on;
        add_header X-Content-Type-Options nosniff;
        if ($ssl_protocol = "") {
          return 308 https://$host$request_uri;
        }
        # index index.html;
        access_log /var/log/nginx/http.access.log combined;
        error_log /var/log/nginx/http.error.log;
        # root /usr/share/nginx/html/cloudmason.org;
        # location ~ \.php$ {
        #   try_files $uri =404;
        #   fastcgi_pass unix:/run/php/php7.3-fpm.sock;
        #   include /etc/nginx/fastcgi_params;
        #   fastcgi_index index.php;
        #   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        # }
      }
      server {
        listen *:443 ssl;
        server_name cloudmason.org;
        ssl_certificate /etc/nginx/cloudmason.org/crypto/fullchain.pem;
        ssl_certificate_key /etc/nginx/cloudmason.org/crypto/privkey.pem;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;
        root /usr/share/nginx/html/cloudmason.org;
        index index.php index.html index.htm;
        location / {
          try_files $uri $uri/ index.php =404;
        }
        # error_page 404 /404.html;
        # error_page 500 502 503 504 /50x.html;
        # location = /50x.html {
        #   root /usr/share/nginx/html;
        # }
        location ~ \.php$ {
          try_files $uri =404;
          fastcgi_pass unix:/run/php/php7.3-fpm.sock;
          include /etc/nginx/fastcgi_params;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
      }
      #   location ~ .php$ {
      #     try_files $uri =404;
      #     fastcgi_pass 127.0.0.1:9000;
      #     fastcgi_index index.php;
      #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      #     include fastcgi_params;
      #   }
      #   access_log   /var/log/nginx/https.access.log combined;
      #   error_log    /var/log/nginx/https.error.log;
      #   add_header   Front-End-Https on;
      #   add_header   X-Content-Type-Options nosniff;
      #   add_header   Access-Control-Allow-Origin *;
      #   add_header   Content-Security-Policy "frame-ancestors cloudmason.org";
      # }
  become: yes
  notify: Reload nginx

- name: Start and enable nginx and php7.3-fpm
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - php7.3-fpm
  become: yes

- name: Create cloudmason.org base directory
  file:
    state: directory
    path: /usr/share/nginx/html/cloudmason.org
    owner: root
    group: root
    mode: 0755
  become: yes
  notify: Reload nginx

# - name: Deploy stock site
#   copy:
#     dest: /usr/share/nginx/html/cloudmason.org/index.html
#     owner: root
#     group: root
#     mode: 0644
#     content: |
#       <html>
#       <head>
#         <title>Hello, World</title>
#       </head>
#       <body>
#         Hello, World
#       </body>
#       </html>
#   become: yes

# - name: Deploy phpinfo page
#   copy:
#     dest: /usr/share/nginx/html/cloudmason.org/phpinfo.php
#     owner: root
#     group: root
#     mode: 0644
#     content: |
#       <?php
#       phpinfo();
#       ?>
#   become: yes

- name: Create nginx crypto directory
  file:
    state: directory
    path: /etc/nginx/cloudmason.org/crypto
    owner: root
    group: root
    mode: 0750
    recurse: yes
  become: yes
  notify: Reload nginx

- name: Deploy nginx crypto
  copy:
    src: "cloudmason.org/crypto/{{ item }}"
    dest: "/etc/nginx/cloudmason.org/crypto/{{ item }}"
    owner: root
    group: root
    mode: 0640
    backup: yes
  become: yes
  notify: Reload nginx
  loop:
    - cert.pem
    - chain.pem
    - fullchain.pem
    - privkey.pem

- name: Deploy cloudmason.org site
  copy:
    src: "cloudmason.org/{{ item }}"
    dest: "/usr/share/nginx/html/cloudmason.org/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  loop:
    - android-chrome-192x192.png
    - android-chrome-512x512.png
    - apple-touch-icon.png
    - favicon-16x16.png
    - favicon-32x32.png
    - favicon.ico

- name: Deploy cloudmason.org site
  template:
    src: "cloudmason.org/{{ item }}"
    dest: "/usr/share/nginx/html/cloudmason.org/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  loop:
    - README.md
    - cloudmason.php
    - graphs.php
    - index.php
    - keybase.txt
    - media.php
    - site.webmanifest

- name: Symlink cloudmason.php to index.php
  file:
    state: link
    src: /usr/share/nginx/html/cloudmason.org/cloudmason.php
    dest: /usr/share/nginx/html/cloudmason.org/index.php
    force: yes
  become: yes

- name: Install fping and fortune
  apt:
    state: present
    name:
      - fping
      - fortune
  become: yes

- name: Install cron ping thing
  cron:
    name: cron-ping-thing
    job: /usr/bin/fping -a -d -q -g 192.168.1.0/24 2>/dev/null | sed -E 's,.cloudmason.org$,,' | paste -sd' ' >/usr/share/nginx/html/cloudmason.org/cloudmason
    user: root
    minute: "15"
  become: yes
