---

- name: Install nginx and php-fpm
  apt:
    state: present
    name:
      - nginx
      - php-fpm
  become: yes

- name: Check if /etc/nginx/sites-enabled/default exists
  stat:
    path: /etc/nginx/sites-enabled/default
  register: default
  become: yes

- name: Move /etc/nginx/sites-enabled/default out of the way
  shell: rm -f /etc/nginx/sites-enabled/default
  when: default.stat.islnk is defined
  notify: Reload nginx
  become: yes

- name: Deploy /etc/nginx/conf.d/default.conf
  copy:
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    content: |
      server {
        listen *:80 default_server;
        # add_header Front-End-Https on;
        # add_header X-Content-Type-Options nosniff;
        # if ($ssl_protocol = "") {
        #   return 308 https://$host$request_uri;
        # }
        index index.html;
        access_log /var/log/nginx/http.access.log combined;
        error_log /var/log/nginx/http.error.log;
        root /usr/share/nginx/html;
        location ~ \.php$ {
          fastcgi_pass unix:/run/php/php7.3-fpm.sock;
          include /etc/nginx/fastcgi_params;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
      }
      # server {
      #   listen *:443 ssl;
      #   server_name cloudmason.org;
      #   ssl_certificate     /etc/letsencrypt/live/cloudmason.org/fullchain.pem;
      #   ssl_certificate_key /etc/letsencrypt/live/cloudmason.org/privkey.pem;
      #   ssl_session_cache   shared:SSL:10m;
      #   ssl_session_timeout 5m;
      #   ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
      #   ssl_ciphers         EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4;
      #   ssl_prefer_server_ciphers on;
      #   root   /usr/share/nginx/html/cloudmason.org;
      #   index  index.php index.html index.htm;
      #   location / {
      #     try_files $uri $uri/ =404;
      #   }
      #   error_page 404 /404.html;
      #   error_page 500 502 503 504 /50x.html;
      #   location = /50x.html {
      #     root /usr/share/nginx/html;
      #   }
      #   location ~ .php$ {
      #     try_files $uri =404;
      #     fastcgi_pass 127.0.0.1:9000;
      #     fastcgi_index index.php;
      #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      #     include fastcgi_params;
      #   }
      #   access_log   /var/log/nginx/https.access.log combined;
      #   error_log    /var/log/nginx/https.error.log;
      #   add_header   Front-End-Https on;
      #   add_header   X-Content-Type-Options nosniff;
      #   add_header   Access-Control-Allow-Origin *;
      #   add_header   Content-Security-Policy "frame-ancestors cloudmason.org";
      # }
  become: yes
  notify: Reload nginx

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Deploy stock site
  copy:
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: 0644
    content: |
      <html>
      <head>
        <title>Hello, World</title>
      </head>
      <body>
        Hello, World
      </body>
      </html>
  become: yes
