---

- name: Install nginx and php-fpm
  apt:
    state: present
    name:
      - nginx
      - php-fpm
  become: yes

- name: Check if /etc/nginx/sites-enabled/default exists
  stat:
    path: /etc/nginx/sites-enabled/default
  register: default
  become: yes

- name: Move /etc/nginx/sites-enabled/default out of the way
  shell: rm -f /etc/nginx/sites-enabled/default
  when: default.stat.islnk is defined
  notify: Reload nginx
  become: yes

- name: Deploy /etc/nginx/conf.d/default.conf
  copy:
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    content: |
      server {
        listen *:8000 default_server;
        access_log /var/log/nginx/http.access.log combined;
        error_log /var/log/nginx/http.error.log;
        root /usr/share/nginx/html/cloudmason.org;
        index index.php index.html index.htm;
        location / {
          try_files $uri $uri/ index.php =404;
        }
        location ~ \.php$ {
          try_files $uri =404;
          fastcgi_pass unix:/run/php/php7.3-fpm.sock;
          include /etc/nginx/fastcgi_params;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
      }
  become: yes
  notify: Reload nginx

- name: Start and enable nginx and php7.3-fpm
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - php7.3-fpm
  become: yes

- name: Create cloudmason.org base directory
  file:
    state: directory
    path: /usr/share/nginx/html/cloudmason.org
    owner: root
    group: root
    mode: 0755
  become: yes
  notify: Reload nginx

- name: Deploy cloudmason.org site
  copy:
    src: "cloudmason.org/{{ item }}"
    dest: "/usr/share/nginx/html/cloudmason.org/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  loop:
    - android-chrome-192x192.png
    - android-chrome-512x512.png
    - apple-touch-icon.png
    - favicon-16x16.png
    - favicon-32x32.png
    - favicon.ico

- name: Deploy cloudmason.org site
  template:
    src: "cloudmason.org/{{ item }}"
    dest: "/usr/share/nginx/html/cloudmason.org/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  loop:
    - README.md
    - cloudmason.php
    - graphs.php
    - index.php
    - keybase.txt
    - media.php
    - site.webmanifest

- name: Symlink cloudmason.php to index.php
  file:
    state: link
    src: /usr/share/nginx/html/cloudmason.org/cloudmason.php
    dest: /usr/share/nginx/html/cloudmason.org/index.php
    force: yes
  become: yes

- name: Install fping, fortune and fortunes
  apt:
    state: present
    name:
      - fping
      - fortune
      - fortunes
      - fortunes-bofh-excuses
  become: yes

- name: Install cron ping thing
  cron:
    name: cron-ping-thing
    job: /usr/bin/fping -a -d -q -g 192.168.1.0/24 2>/dev/null | sed -E 's,.cloudmason.org$,,' | paste -sd' ' >/usr/share/nginx/html/cloudmason.org/cloudmason
    user: root
    minute: "15"
  become: yes

- name: Lay down /usr/local/bin/sshbrutes.sh
  copy:
    dest: /usr/local/bin/sshbrutes.sh
    owner: root
    group: root
    mode: 0755
    content: |
      #!/usr/bin/env bash
      IFS=$'\n'
      for x in $(sudo grep "$(date '+%b %d')" /var/log/auth.log | grep 'Bye Bye \[preauth\]' | grep -v grep | awk '{print $9}' | sort -nr | uniq -c); do
        count="$(echo $x | awk '{print $1}')"
        ip="$(echo $x | awk '{print $2}')"
        host="$(dig -x $ip +short)"
        if [[ -n "$host" ]]; then
          host="(${host})"
        fi
        echo "$ip $host $count"
      done
  become: yes

- name: Install cron ssh brutes
  cron:
    name: cron-ssh-brutes
    job: /usr/local/bin/sshbrutes.sh >/usr/share/nginx/html/cloudmason.org/sshbrutes
    user: root
    minute: "30"
  become: yes
