---

slack_notify: &slack_notify
  on_success:
    put: slack-alert
    params:
      alert_type: success
  on_failure:
    put: slack-alert
    params:
      alert_type: failed
  on_abort:
    put: slack-alert
    params:
      alert_type: aborted
  on_error:
    put: slack-alert
    params:
      alert_type: errored

resource_types:

  - name: slack-alert
    type: docker-image
    source:
      repository: arbourd/concourse-slack-alert-resource

resources:

  - name: src
    type: git
    source:
      uri: https://github.com/mamercad/cloudmason.git
      branch: main

  - name: slack-alert
    type: slack-alert
    source:
      url: ((SLACK_WEBHOOK))

jobs:

  - name: ci-image
    plan:

      - get: src
        trigger: false

      - task: docker
        privileged: true
        config:
          params:
            SHELL: /bin/bash
            IMAGE: mamercad/cloudmason
            TAG: latest
            CONCOURSE_TARGET: cloudmason
            PIPELINE: cloudmason
            JOB: job
            DOCKER_IO_USERNAME: ((DOCKER_IO_USERNAME))
            DOCKER_IO_PASSWORD: ((DOCKER_IO_PASSWORD))
          inputs:
            - name: src
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: amidos/dcind
          run:
            path: bash
            args:
              - -ec
              - |
                source /docker-lib.sh
                start_docker
                cd src/ci
                echo "$DOCKER_IO_PASSWORD" | base64 -d | docker login --username $DOCKER_IO_USERNAME --password-stdin
                make build
                make push

    <<: *slack_notify

  - name: ansible
    plan:

      - get: src
        trigger: false

      - task: ping
        config:
          params:
            ANSIBLE_FORCE_COLOR: true
            CONCOURSE_SSH_KEY: ((CONCOURSE_SSH_KEY))
          inputs:
            - name: src
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: mamercad/cloudmason
          run:
            path: bash
            args:
              - -c
              - |
                stty cols 120
                cd src/ansible
                ansible --version
                echo
                touch ~/concourse.key
                chmod 600 ~/concourse.key
                echo "$CONCOURSE_SSH_KEY" | base64 -d > ~/concourse.key
                eval $(ssh-agent)
                ssh-add ~/concourse.key
                ssh-add -l
                echo
                ansible -i inventory.yml -m ping all

    <<: *slack_notify
