---
- name: argocd
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: include argocd role (main tasks)
      ansible.builtin.include_role:
        name: argocd
        tasks_from: main.yml
      vars:
        manifest: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        context: lenovo
        namespace: argocd
