#!/usr/bin/env pipenv run ansible-playbook -i inventory/cloudmason.yml --vault-password-file .vault_pass -v
---

- name: cloudmason.org
  hosts: cloudmason.org
  gather_facts: no
  become: no
  roles:
    - cloudmason.org
