---
- name: concourse
  hosts: all
  connection: ssh
  gather_facts: false
  become: false

  tasks:

    - name: include concourse role (user tasks)
      ansible.builtin.include_role:
        name: concourse
        tasks_from: user.yml
