---
- name: Debug
  hosts: all
  gather_facts: yes

  tasks:

    - shell: |
        pwd;
        ls -la;
        cat collections/requirements.yml;

    - include_role:
        name: slack
      vars:
        slack_channel: "#bots"
        slack_message: "Yo!"
