---

- name: awx
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - awx

#- name: ubuntu
#  hosts: ubuntu
#  gather_facts: yes
#  become: no
#  roles:
#    - ubuntu
#
#- name: pi
#  hosts: pi
#  gather_facts: yes
#  become: no
#  roles:
#    - pi
