---

- name: awx
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - awx
  tags:
    - awx

- name: ubuntu
  hosts: ubuntu
  gather_facts: yes
  become: no
  roles:
    - ubuntu
  tags:
    - ubuntu

- name: pi
  hosts: pi
  gather_facts: yes
  become: no
  roles:
    - pi
  tags:
    - pi
