---

- name: awx
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - awx
  tags:
    - awx

- name: ubuntu
  hosts: ubuntu
  gather_facts: true
  become: false
  roles:
    - ubuntu
  tags:
    - ubuntu

- name: pi
  hosts: pi
  gather_facts: yes
  become: false
  roles:
    - pi
  tags:
    - pi
