---

- name: awx
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - awx
  tags:
    - awx

- name: ubuntu
  hosts: ubuntu
  gather_facts: true
  become: false
  roles:
    - ubuntu
  tags:
    - ubuntu

- name: pi
  hosts: pi
  gather_facts: true
  become: false
  roles:
    - pi
  tags:
    - pi

- name: zabbix / server
  hosts: zabbix_servers
  gather_facts: true
  become: false
  tasks:
    - name: Include zabbix / server
      ansible.builtin.include_role:
        name: zabbix
        tasks_from: server.yml
    - name: Include zabbix / config
      ansible.builtin.include_role:
        name: zabbix
        tasks_from: config.yml
  tags:
    - zabbix

- name: zabbix / agent
  hosts: zabbix_clients
  gather_facts: true
  become: false
  tasks:
    - name: Include zabbix / agent
      ansible.builtin.include_role:
        name: zabbix
        tasks_from: agent.yml
  tags:
    - zabbix
