#!/usr/bin/env pipenv run ansible-playbook -i inventory/cloudmason.yml --vault-password-file .vault_pass -v
---

- name: ubuntu-chef
  hosts: chef
  gather_facts: no
  become: no
  roles:
    - ubuntu-chef
