---
- name: vault
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: include vault role (main tasks)
      ansible.builtin.include_role:
        name: vault
        tasks_from: main.yml
      vars:
        context: lenovo
        namespace: vault
        helm:
          chart_ref: hashicorp/vault
          chart_version: 0.17.1
          helm_values:
            server:
              ha:
                enabled: true
                replicas: 3
                raft:
                  enabled: true
                  setNodeId: true
            ui:
              enabled: true
              serviceType: "LoadBalancer"
              serviceNodePort: null
              externalPort: 8200
