---

- name: Install snapd
  apt:
    state: present
    name: snapd
  become: yes

- name: Install microk8s
  community.general.snap:
    state: present
    name: microk8s
    classic: yes
    channel: '1.19'
  become: yes

- name: Enable microk8s services
  command: microk8s enable dns storage
  become: yes

- name: Add mark to microk8s group
  user:
    name: mark
    groups:
      - microk8s
    append: yes
  become: yes
