- name: create {{ namespace }} namespace
  kubernetes.core.k8s:
    state: present
    context: "{{ context }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd

- name: download argocd install
  ansible.builtin.get_url:
    url: "{{ manifest }}"
    dest: /tmp/argocd.yml
    mode: 0644

- name: apply argocd install
  kubernetes.core.k8s:
    state: present
    context: "{{ context }}"
    namespace: "{{ namespace }}"
    src: /tmp/argocd.yml

- name: patch argocd service (LoadBalancer)
  kubernetes.core.k8s_json_patch:
    context: "{{ context }}"
    namespace: "{{ namespace }}"
    api_version: v1
    kind: Service
    name: argocd-server
    patch:
      - op: replace
        path: /spec/type
        value: LoadBalancer

- name: get admin secret
  kubernetes.core.k8s_info:
    context: "{{ context }}"
    namespace: "{{ namespace }}"
    api_version: v1
    kind: Secret
    name: argocd-initial-admin-secret
  register: admin_secret

- name: show admin password
  ansible.builtin.debug:
    msg: |
      argo admin password: {{ admin_secret.resources.0.data.password | b64decode }}
