---

- name: Add default repository
  community.kubernetes.helm_repository:
    name: stable
    repo_url: https://charts.helm.sh/stable
  delegate_to: localhost

- name: Add bitnami chart repo
  community.kubernetes.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
  delegate_to: localhost

- name: Create the metallb namespace
  community.kubernetes.k8s:
    state: present
    context: "{{ context }}"
    name: metallb
    api_version: v1
    kind: Namespace
  delegate_to: localhost

- name: Download metallb namespace manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/namespace.yaml
    dest: /tmp/metallb-namespace.yml
    mode: 0664
  delegate_to: localhost
  when:
    - metallb is defined

- name: Apply metallb namespace manifest
  community.kubernetes.k8s:
    state: present
    context: "{{ context }}"
    src: /tmp/metallb-namespace.yml
  delegate_to: localhost
  when:
    - metallb is defined

- name: Download metallb manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/metallb.yaml
    dest: /tmp/metallb.yml
    mode: 0664
  delegate_to: localhost
  when:
    - metallb is defined

- name: Apply metallb manifest
  community.kubernetes.k8s:
    state: present
    context: "{{ context }}"
    src: /tmp/metallb.yml
  delegate_to: localhost
  when:
    - metallb is defined

- name: Create metallb memberlist secret
  community.kubernetes.k8s:
    state: present
    context: "{{ context }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        namespace: metallb-system
        name: memberlist
      data:
        secretkey: "{{ metallb.memberlist | b64encode }}"
  delegate_to: localhost
  when:
    - metallb is defined

- name: Create metallb configmap
  community.kubernetes.k8s:
    state: present
    context: "{{ context }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - "{{ metallb.range }}"
  delegate_to: localhost
  when:
    - metallb is defined
