---

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted
  become: yes

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
  become: yes

- name: Restart pdns
  systemd:
    name: pdns
    state: restarted
    daemon_reload: yes
  become: yes

- name: Restart pdns-recursor
  systemd:
    name: pdns-recursor
    state: restarted
    daemon_reload: yes
  become: yes
