name: ansible-lint

on:
  pull_request:
  push:

jobs:

  ansible-lint:

    name: ansible-lint

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mamercad/cloudmason/ansible

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: mamercad/cloudmason

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install ansible
        run: pip install ansible

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint site.yml -v
